////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// OAD_BG styles..


/////////////////////////////////////////////////////
// OAD_BG_TOP styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Bg_Top_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_40 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_45 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_46 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_47 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_BTN_PANE styles..


/////////////////////////////////////////////////////
// OAD_BTN_YES styles..


/////////////////////////////////////////////////////
// OAD_BTN_YES_LEFT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Btn_Yes_Left_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_53 },
    { CP_NOON, 0 },
};
#define _Zui_Oad_Btn_Yes_Left_Arrow_Focus_DrawStyle _Zui_Oad_Btn_Yes_Left_Arrow_Normal_DrawStyle

/////////////////////////////////////////////////////
// OAD_BTN_YES_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Btn_Yes_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_808 },
    { CP_NOON, 0 },
};
#define _Zui_Oad_Btn_Yes_Text_Focus_DrawStyle _Zui_Oad_Btn_Yes_Text_Normal_DrawStyle

/////////////////////////////////////////////////////
// OAD_BTN_NO styles..


/////////////////////////////////////////////////////
// OAD_BTN_NO_RIGHT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Btn_No_Right_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_55 },
    { CP_NOON, 0 },
};
#define _Zui_Oad_Btn_No_Right_Arrow_Focus_DrawStyle _Zui_Oad_Btn_No_Right_Arrow_Normal_DrawStyle

/////////////////////////////////////////////////////
// OAD_BTN_NO_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Btn_No_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_810 },
    { CP_NOON, 0 },
};
#define _Zui_Oad_Btn_No_Text_Focus_DrawStyle _Zui_Oad_Btn_No_Text_Normal_DrawStyle

/////////////////////////////////////////////////////
// OAD_BTN_EXIT styles..


/////////////////////////////////////////////////////
// OAD_BTN_EXIT_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Btn_Exit_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1216 },
    { CP_NOON, 0 },
};
#define _Zui_Oad_Btn_Exit_Text_Focus_DrawStyle _Zui_Oad_Btn_Exit_Text_Normal_DrawStyle

/////////////////////////////////////////////////////
// OAD_TEXT_PANE styles..


/////////////////////////////////////////////////////
// OAD_TEXT1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Text1_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1217 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_TEXT2 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Text2_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_480 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_TEXT3 styles..

#define _Zui_Oad_Text3_Normal_DrawStyle _Zui_Oad_Text2_Normal_DrawStyle

/////////////////////////////////////////////////////
// OAD_VERSION_PANE styles..


/////////////////////////////////////////////////////
// OAD_TV_VERSION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Tv_Version_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1218 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_TS_VERSION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Ts_Version_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1219 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_YES_TO_UPGRADE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Yes_To_Upgrade_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1220 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// OAD_IGNORE_UPGRADE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Oad_Ignore_Upgrade_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1221 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// NZ_OAD_VERSION_PANE styles..


/////////////////////////////////////////////////////
// NZ_OAD_TV_VERSION styles..

#define _Zui_Nz_Oad_Tv_Version_Normal_DrawStyle _Zui_Oad_Tv_Version_Normal_DrawStyle

/////////////////////////////////////////////////////
// NZ_OAD_TS_VERSION styles..

#define _Zui_Nz_Oad_Ts_Version_Normal_DrawStyle _Zui_Oad_Ts_Version_Normal_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Oad[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_OAD_BG
    { NULL, NULL, NULL     },

    // 2 = HWND_OAD_BG_TOP
    { _Zui_Oad_Bg_Top_Normal_DrawStyle, NULL, NULL     },

    // 3 = HWND_OAD_BG_L
    { _Zui_Oad_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // 4 = HWND_OAD_BG_C
    { _Zui_Oad_Bg_C_Normal_DrawStyle, NULL, NULL     },

    // 5 = HWND_OAD_BG_R
    { _Zui_Oad_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // 6 = HWND_OAD_BTN_PANE
    { NULL, NULL, NULL     },

    // 7 = HWND_OAD_BTN_YES
    { NULL, NULL, NULL     },

    // 8 = HWND_OAD_BTN_YES_LEFT_ARROW
    { _Zui_Oad_Btn_Yes_Left_Arrow_Normal_DrawStyle, _Zui_Oad_Btn_Yes_Left_Arrow_Focus_DrawStyle, NULL     },

    // 9 = HWND_OAD_BTN_YES_TEXT
    { _Zui_Oad_Btn_Yes_Text_Normal_DrawStyle, _Zui_Oad_Btn_Yes_Text_Focus_DrawStyle, NULL     },

    // 10 = HWND_OAD_BTN_NO
    { NULL, NULL, NULL     },

    // 11 = HWND_OAD_BTN_NO_RIGHT_ARROW
    { _Zui_Oad_Btn_No_Right_Arrow_Normal_DrawStyle, _Zui_Oad_Btn_No_Right_Arrow_Focus_DrawStyle, NULL     },

    // 12 = HWND_OAD_BTN_NO_TEXT
    { _Zui_Oad_Btn_No_Text_Normal_DrawStyle, _Zui_Oad_Btn_No_Text_Focus_DrawStyle, NULL     },

    // 13 = HWND_OAD_BTN_EXIT
    { NULL, NULL, NULL     },

    // 14 = HWND_OAD_BTN_EXIT_TEXT
    { _Zui_Oad_Btn_Exit_Text_Normal_DrawStyle, _Zui_Oad_Btn_Exit_Text_Focus_DrawStyle, NULL     },

    // 15 = HWND_OAD_TEXT_PANE
    { NULL, NULL, NULL     },

    // 16 = HWND_OAD_TEXT1
    { _Zui_Oad_Text1_Normal_DrawStyle, NULL, NULL     },

    // 17 = HWND_OAD_TEXT2
    { _Zui_Oad_Text2_Normal_DrawStyle, NULL, NULL     },

    // 18 = HWND_OAD_TEXT3
    { _Zui_Oad_Text3_Normal_DrawStyle, NULL, NULL     },

    // 19 = HWND_OAD_VERSION_PANE
    { NULL, NULL, NULL     },

    // 20 = HWND_OAD_TV_VERSION
    { _Zui_Oad_Tv_Version_Normal_DrawStyle, NULL, NULL     },

    // 21 = HWND_OAD_TS_VERSION
    { _Zui_Oad_Ts_Version_Normal_DrawStyle, NULL, NULL     },

    // 22 = HWND_OAD_YES_TO_UPGRADE
    { _Zui_Oad_Yes_To_Upgrade_Normal_DrawStyle, NULL, NULL     },

    // 23 = HWND_OAD_IGNORE_UPGRADE
    { _Zui_Oad_Ignore_Upgrade_Normal_DrawStyle, NULL, NULL     },

    // 24 = HWND_NZ_OAD_VERSION_PANE
    { NULL, NULL, NULL     },

    // 25 = HWND_NZ_OAD_TV_VERSION
    { _Zui_Nz_Oad_Tv_Version_Normal_DrawStyle, NULL, NULL     },

    // 26 = HWND_NZ_OAD_TS_VERSION
    { _Zui_Nz_Oad_Ts_Version_Normal_DrawStyle, NULL, NULL     },

};
