////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// INSTALL_BACKGROUND styles..


/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_TOP styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Background_Top_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_27 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Background_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_58 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Background_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_59 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Background_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_60 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_OK_BTN styles..


/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_BAR1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Background_Bar1_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_61 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_BAR2 styles..

#define _Zui_Install_Background_Bar2_Normal_DrawStyle _Zui_Install_Background_Bar1_Normal_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_BAR3 styles..

#define _Zui_Install_Background_Bar3_Normal_DrawStyle _Zui_Install_Background_Bar1_Normal_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_BACKGROUND_BAR4 styles..

#define _Zui_Install_Background_Bar4_Normal_DrawStyle _Zui_Install_Background_Bar1_Normal_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE styles..


/////////////////////////////////////////////////////
// INSTALL_MAIN_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_953 },
    { CP_NOON, 0 },
};
#define _Zui_Install_Main_Title_Focus_DrawStyle _Zui_Install_Main_Title_Normal_DrawStyle
#define _Zui_Install_Main_Title_Disabled_DrawStyle _Zui_Install_Main_Title_Normal_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID styles..


/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid1_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_436 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid1_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_3 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_464 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID2 styles..

#define _Zui_Install_Main_Page_Grid2_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid2_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID_LEFT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Left_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_62 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Left_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_63 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID3 styles..

#define _Zui_Install_Main_Page_Grid3_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid3_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID4 styles..

#define _Zui_Install_Main_Page_Grid4_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid4_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID5 styles..

#define _Zui_Install_Main_Page_Grid5_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid5_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID6 styles..

#define _Zui_Install_Main_Page_Grid6_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid6_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID7 styles..

#define _Zui_Install_Main_Page_Grid7_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid7_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID_UP_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Up_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_64 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Up_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_65 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID8 styles..

#define _Zui_Install_Main_Page_Grid8_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid8_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID9 styles..

#define _Zui_Install_Main_Page_Grid9_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid9_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID_DOWN_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Down_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_66 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Down_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_67 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID10 styles..

#define _Zui_Install_Main_Page_Grid10_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid10_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID11 styles..

#define _Zui_Install_Main_Page_Grid11_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid11_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID12 styles..

#define _Zui_Install_Main_Page_Grid12_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid12_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID13 styles..

#define _Zui_Install_Main_Page_Grid13_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid13_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID14 styles..

#define _Zui_Install_Main_Page_Grid14_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid14_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID_RIGHT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Right_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_68 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Page_Grid_Right_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_69 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_MAIN_PAGE_GRID15 styles..

#define _Zui_Install_Main_Page_Grid15_Normal_DrawStyle _Zui_Install_Main_Page_Grid1_Normal_DrawStyle
#define _Zui_Install_Main_Page_Grid15_Focus_DrawStyle _Zui_Install_Main_Page_Grid1_Focus_DrawStyle

/////////////////////////////////////////////////////
// INSTALL_MAIN_TEXT_1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Text_1_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_954 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Text_1_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_955 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Text_1_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_956 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// INSTALL_MAIN_TEXT_2 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Text_2_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_957 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Text_2_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_958 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Install_Main_Text_2_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_959 },
    { CP_NOON, 0 },
};

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Install_Guide[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_INSTALL_BACKGROUND
    { NULL, NULL, NULL     },

    // 2 = HWND_INSTALL_BACKGROUND_TOP
    { _Zui_Install_Background_Top_Normal_DrawStyle, NULL, NULL     },

    // 3 = HWND_INSTALL_BACKGROUND_L
    { _Zui_Install_Background_L_Normal_DrawStyle, NULL, NULL     },

    // 4 = HWND_INSTALL_BACKGROUND_C
    { _Zui_Install_Background_C_Normal_DrawStyle, NULL, NULL     },

    // 5 = HWND_INSTALL_BACKGROUND_R
    { _Zui_Install_Background_R_Normal_DrawStyle, NULL, NULL     },

    // 6 = HWND_INSTALL_BACKGROUND_OK_BTN
    { NULL, NULL, NULL     },

    // 7 = HWND_INSTALL_BACKGROUND_BAR1
    { _Zui_Install_Background_Bar1_Normal_DrawStyle, NULL, NULL     },

    // 8 = HWND_INSTALL_BACKGROUND_BAR2
    { _Zui_Install_Background_Bar2_Normal_DrawStyle, NULL, NULL     },

    // 9 = HWND_INSTALL_BACKGROUND_BAR3
    { _Zui_Install_Background_Bar3_Normal_DrawStyle, NULL, NULL     },

    // 10 = HWND_INSTALL_BACKGROUND_BAR4
    { _Zui_Install_Background_Bar4_Normal_DrawStyle, NULL, NULL     },

    // 11 = HWND_INSTALL_MAIN_PAGE
    { NULL, NULL, NULL     },

    // 12 = HWND_INSTALL_MAIN_TITLE
    { _Zui_Install_Main_Title_Normal_DrawStyle, _Zui_Install_Main_Title_Focus_DrawStyle, _Zui_Install_Main_Title_Disabled_DrawStyle     },

    // 13 = HWND_INSTALL_MAIN_PAGE_GRID
    { NULL, NULL, NULL     },

    // 14 = HWND_INSTALL_MAIN_PAGE_GRID1
    { _Zui_Install_Main_Page_Grid1_Normal_DrawStyle, _Zui_Install_Main_Page_Grid1_Focus_DrawStyle, NULL     },

    // 15 = HWND_INSTALL_MAIN_PAGE_GRID2
    { _Zui_Install_Main_Page_Grid2_Normal_DrawStyle, _Zui_Install_Main_Page_Grid2_Focus_DrawStyle, NULL     },

    // 16 = HWND_INSTALL_MAIN_PAGE_GRID_LEFT_ARROW
    { _Zui_Install_Main_Page_Grid_Left_Arrow_Normal_DrawStyle, _Zui_Install_Main_Page_Grid_Left_Arrow_Focus_DrawStyle, NULL     },

    // 17 = HWND_INSTALL_MAIN_PAGE_GRID3
    { _Zui_Install_Main_Page_Grid3_Normal_DrawStyle, _Zui_Install_Main_Page_Grid3_Focus_DrawStyle, NULL     },

    // 18 = HWND_INSTALL_MAIN_PAGE_GRID4
    { _Zui_Install_Main_Page_Grid4_Normal_DrawStyle, _Zui_Install_Main_Page_Grid4_Focus_DrawStyle, NULL     },

    // 19 = HWND_INSTALL_MAIN_PAGE_GRID5
    { _Zui_Install_Main_Page_Grid5_Normal_DrawStyle, _Zui_Install_Main_Page_Grid5_Focus_DrawStyle, NULL     },

    // 20 = HWND_INSTALL_MAIN_PAGE_GRID6
    { _Zui_Install_Main_Page_Grid6_Normal_DrawStyle, _Zui_Install_Main_Page_Grid6_Focus_DrawStyle, NULL     },

    // 21 = HWND_INSTALL_MAIN_PAGE_GRID7
    { _Zui_Install_Main_Page_Grid7_Normal_DrawStyle, _Zui_Install_Main_Page_Grid7_Focus_DrawStyle, NULL     },

    // 22 = HWND_INSTALL_MAIN_PAGE_GRID_UP_ARROW
    { _Zui_Install_Main_Page_Grid_Up_Arrow_Normal_DrawStyle, _Zui_Install_Main_Page_Grid_Up_Arrow_Focus_DrawStyle, NULL     },

    // 23 = HWND_INSTALL_MAIN_PAGE_GRID8
    { _Zui_Install_Main_Page_Grid8_Normal_DrawStyle, _Zui_Install_Main_Page_Grid8_Focus_DrawStyle, NULL     },

    // 24 = HWND_INSTALL_MAIN_PAGE_GRID9
    { _Zui_Install_Main_Page_Grid9_Normal_DrawStyle, _Zui_Install_Main_Page_Grid9_Focus_DrawStyle, NULL     },

    // 25 = HWND_INSTALL_MAIN_PAGE_GRID_DOWN_ARROW
    { _Zui_Install_Main_Page_Grid_Down_Arrow_Normal_DrawStyle, _Zui_Install_Main_Page_Grid_Down_Arrow_Focus_DrawStyle, NULL     },

    // 26 = HWND_INSTALL_MAIN_PAGE_GRID10
    { _Zui_Install_Main_Page_Grid10_Normal_DrawStyle, _Zui_Install_Main_Page_Grid10_Focus_DrawStyle, NULL     },

    // 27 = HWND_INSTALL_MAIN_PAGE_GRID11
    { _Zui_Install_Main_Page_Grid11_Normal_DrawStyle, _Zui_Install_Main_Page_Grid11_Focus_DrawStyle, NULL     },

    // 28 = HWND_INSTALL_MAIN_PAGE_GRID12
    { _Zui_Install_Main_Page_Grid12_Normal_DrawStyle, _Zui_Install_Main_Page_Grid12_Focus_DrawStyle, NULL     },

    // 29 = HWND_INSTALL_MAIN_PAGE_GRID13
    { _Zui_Install_Main_Page_Grid13_Normal_DrawStyle, _Zui_Install_Main_Page_Grid13_Focus_DrawStyle, NULL     },

    // 30 = HWND_INSTALL_MAIN_PAGE_GRID14
    { _Zui_Install_Main_Page_Grid14_Normal_DrawStyle, _Zui_Install_Main_Page_Grid14_Focus_DrawStyle, NULL     },

    // 31 = HWND_INSTALL_MAIN_PAGE_GRID_RIGHT_ARROW
    { _Zui_Install_Main_Page_Grid_Right_Arrow_Normal_DrawStyle, _Zui_Install_Main_Page_Grid_Right_Arrow_Focus_DrawStyle, NULL     },

    // 32 = HWND_INSTALL_MAIN_PAGE_GRID15
    { _Zui_Install_Main_Page_Grid15_Normal_DrawStyle, _Zui_Install_Main_Page_Grid15_Focus_DrawStyle, NULL     },

    // 33 = HWND_INSTALL_MAIN_TEXT_1
    { _Zui_Install_Main_Text_1_Normal_DrawStyle, _Zui_Install_Main_Text_1_Focus_DrawStyle, _Zui_Install_Main_Text_1_Disabled_DrawStyle     },

    // 34 = HWND_INSTALL_MAIN_TEXT_2
    { _Zui_Install_Main_Text_2_Normal_DrawStyle, _Zui_Install_Main_Text_2_Focus_DrawStyle, _Zui_Install_Main_Text_2_Disabled_DrawStyle     },

};
