////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// CATUNE_TRANSPARENT_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Transparent_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_BG_PANE styles..


/////////////////////////////////////////////////////
// CATUNE_TOP_HALF_BG styles..


/////////////////////////////////////////////////////
// CATUNE_TOP_HALF_LEFT_ICON_BG styles..


/////////////////////////////////////////////////////
// CATUNE_TOP_HALF_LEFT_ICON styles..


/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Bottom_Half_Bg_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_278 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_EXIT_BTN styles..


/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_EXIT_TXT styles..


/////////////////////////////////////////////////////
// CATUNE_TOP_HALF_RIGHT_ICON styles..


/////////////////////////////////////////////////////
// CATUNE_TOP_HALF_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Top_Half_Title_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_40 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1172 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Top_Half_Title_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1173 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Top_Half_Title_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1172 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_LEFT_ARROW styles..


/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_RIGHT_ARROW styles..


/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_UP_ARROW styles..


/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_DOWN_ARROW styles..


/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_BG_L styles..

#define _Zui_Catune_Bottom_Half_Bg_L_Normal_DrawStyle _Zui_Catune_Bottom_Half_Bg_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_BOTTOM_HALF_BG_R styles..

#define _Zui_Catune_Bottom_Half_Bg_R_Normal_DrawStyle _Zui_Catune_Bottom_Half_Bg_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_PAGE_LIST styles..


/////////////////////////////////////////////////////
// CATUNE_FREQUENCY styles..


/////////////////////////////////////////////////////
// CATUNE_FREQUENCY_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Frequency_Bg_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_33 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_FREQUENCY_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Frequency_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1174 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Frequency_Txt_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1175 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_FREQUENCY_OPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Frequency_Option_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_4 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Frequency_Option_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1176 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_SYMBOL styles..


/////////////////////////////////////////////////////
// CATUNE_SYMBOL_BG styles..

#define _Zui_Catune_Symbol_Bg_Focus_DrawStyle _Zui_Catune_Frequency_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SYMBOL_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Symbol_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1177 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Symbol_Txt_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1178 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_SYMBOL_OPTION styles..

#define _Zui_Catune_Symbol_Option_Normal_DrawStyle _Zui_Catune_Frequency_Option_Normal_DrawStyle
#define _Zui_Catune_Symbol_Option_Focus_DrawStyle _Zui_Catune_Frequency_Option_Focus_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_QAM_TYPE styles..


/////////////////////////////////////////////////////
// CATUNE_QAM_TYPE_BG styles..

#define _Zui_Catune_Qam_Type_Bg_Focus_DrawStyle _Zui_Catune_Frequency_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_QAM_TYPE_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Qam_Type_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1179 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Qam_Type_Txt_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1180 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_QAM_TYPE_OPTION styles..

#define _Zui_Catune_Qam_Type_Option_Normal_DrawStyle _Zui_Catune_Frequency_Option_Normal_DrawStyle
#define _Zui_Catune_Qam_Type_Option_Focus_DrawStyle _Zui_Catune_Frequency_Option_Focus_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_SIGNAL_BG styles..


/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_NO_SIGNAL_BTN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_No_Signal_Btn_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_15 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_NO_SIGNAL_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_No_Signal_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_777 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Result_No_Signal_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_No_Signal_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_SEARCHING_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_Searching_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_778 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Result_Searching_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Searching_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_BAD_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Bad_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_779 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Bad_Txt_Focus_DrawStyle _Zui_Catune_Bad_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_NORMAL_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Normal_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_780 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Normal_Txt_Focus_DrawStyle _Zui_Catune_Normal_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_GOOD_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Good_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_781 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Good_Txt_Focus_DrawStyle _Zui_Catune_Good_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SIGNAL_BG styles..


/////////////////////////////////////////////////////
// CATUNE_SIGNAL_BAR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Signal_Bar_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CATUNE_SCAN_ENTERKEY_REMIND_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Enterkey_Remind_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_782 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Enterkey_Remind_Txt_Focus_DrawStyle _Zui_Catune_Scan_Enterkey_Remind_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT styles..


/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_TXT styles..


/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_DTV_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_Dtv_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_487 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Result_Dtv_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Dtv_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_DTV_NUMBER_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_82 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Result_Dtv_Number_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_RADIO_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_Radio_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_775 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Result_Radio_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Radio_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_RADIO_NUMBER_TXT styles..

#define _Zui_Catune_Scan_Result_Radio_Number_Txt_Normal_DrawStyle _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle
#define _Zui_Catune_Scan_Result_Radio_Number_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_DATA_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Catune_Scan_Result_Data_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_776 },
    { CP_NOON, 0 },
};
#define _Zui_Catune_Scan_Result_Data_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Data_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// CATUNE_SCAN_RESULT_DATA_NUMBER_TXT styles..

#define _Zui_Catune_Scan_Result_Data_Number_Txt_Normal_DrawStyle _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle
#define _Zui_Catune_Scan_Result_Data_Number_Txt_Focus_DrawStyle _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVB_SCAN_PAGE styles..


/////////////////////////////////////////////////////
// MENU_DLG_DVB_SCAN_MENU_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_279 },
    { CP_NOON, 0 },
};
#define _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_C_Focus_DrawStyle _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_C_Normal_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVB_SCAN_MENU_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_280 },
    { CP_NOON, 0 },
};
#define _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_L_Focus_DrawStyle _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_L_Normal_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVB_SCAN_MENU_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_281 },
    { CP_NOON, 0 },
};
#define _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_R_Focus_DrawStyle _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_R_Normal_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVB_SCAN_MENU_BG_V styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_V_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_282 },
    { CP_NOON, 0 },
};
#define _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_V_Focus_DrawStyle _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_V_Normal_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVB_SCAN_TYPE_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvb_Scan_Type_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1181 },
    { CP_NOON, 0 },
};
#define _Zui_Menu_Dlg_Dvb_Scan_Type_Text_Focus_DrawStyle _Zui_Menu_Dlg_Dvb_Scan_Type_Text_Normal_DrawStyle

/////////////////////////////////////////////////////
// MENU_DVBC_SCAN_OK_BTN styles..


/////////////////////////////////////////////////////
// MENU_DVBC_SCAN_MENU_BTN styles..


/////////////////////////////////////////////////////
// DVBCSCAN_SCAN_TYPE_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dvbcscan_Scan_Type_Bg_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_19 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_SCAN_TYPE_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Type_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1182 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Type_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1183 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_SCAN_TYPE_OPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Type_Option_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1184 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Type_Option_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1185 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DVBCSCAN_FREQUENCY_BG styles..

#define _Zui_Dvbcscan_Frequency_Bg_Focus_DrawStyle _Zui_Dvbcscan_Scan_Type_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_FREQUENCY_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Frequency_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1186 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Frequency_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1187 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Frequency_Text_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1188 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_SCAN_FREQUENCY_OPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_426 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1189 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_628 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DVBCSCAN_NETWORKID_BG styles..

#define _Zui_Dvbcscan_Networkid_Bg_Focus_DrawStyle _Zui_Dvbcscan_Scan_Type_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_NETWORKID_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Networkid_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1190 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Networkid_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1191 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Networkid_Text_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1192 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_SCAN_NETWORKID_OPTION styles..

#define _Zui_Menu_Dlg_Dvbc_Scan_Networkid_Option_Normal_DrawStyle _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Normal_DrawStyle
#define _Zui_Menu_Dlg_Dvbc_Scan_Networkid_Option_Focus_DrawStyle _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Focus_DrawStyle
#define _Zui_Menu_Dlg_Dvbc_Scan_Networkid_Option_Disabled_DrawStyle _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Disabled_DrawStyle

/////////////////////////////////////////////////////
// DVBCSCAN_SYMBOL_RATE_BG styles..

#define _Zui_Dvbcscan_Symbol_Rate_Bg_Focus_DrawStyle _Zui_Dvbcscan_Scan_Type_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_SYMBOL_RATE_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Symbol_Rate_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1193 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Symbol_Rate_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1194 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Menu_Dlg_Dvbc_Symbol_Rate_Text_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1195 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MENU_DLG_DVBC_SCAN_SYMBOL_RATE_OPTION styles..

#define _Zui_Menu_Dlg_Dvbc_Scan_Symbol_Rate_Option_Normal_DrawStyle _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Normal_DrawStyle
#define _Zui_Menu_Dlg_Dvbc_Scan_Symbol_Rate_Option_Focus_DrawStyle _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Focus_DrawStyle
#define _Zui_Menu_Dlg_Dvbc_Scan_Symbol_Rate_Option_Disabled_DrawStyle _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Disabled_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Cadtv_Manual_Tuning[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_CATUNE_TRANSPARENT_BG
    { _Zui_Catune_Transparent_Bg_Normal_DrawStyle, NULL, NULL     },

    // 2 = HWND_CATUNE_BG_PANE
    { NULL, NULL, NULL     },

    // 3 = HWND_CATUNE_TOP_HALF_BG
    { NULL, NULL, NULL     },

    // 4 = HWND_CATUNE_TOP_HALF_LEFT_ICON_BG
    { NULL, NULL, NULL     },

    // 5 = HWND_CATUNE_TOP_HALF_LEFT_ICON
    { NULL, NULL, NULL     },

    // 6 = HWND_CATUNE_BOTTOM_HALF_BG
    { _Zui_Catune_Bottom_Half_Bg_Normal_DrawStyle, NULL, NULL     },

    // 7 = HWND_CATUNE_BOTTOM_HALF_EXIT_BTN
    { NULL, NULL, NULL     },

    // 8 = HWND_CATUNE_BOTTOM_HALF_EXIT_TXT
    { NULL, NULL, NULL     },

    // 9 = HWND_CATUNE_TOP_HALF_RIGHT_ICON
    { NULL, NULL, NULL     },

    // 10 = HWND_CATUNE_TOP_HALF_TITLE
    { _Zui_Catune_Top_Half_Title_Normal_DrawStyle, _Zui_Catune_Top_Half_Title_Focus_DrawStyle, _Zui_Catune_Top_Half_Title_Disabled_DrawStyle     },

    // 11 = HWND_CATUNE_BOTTOM_HALF_LEFT_ARROW
    { NULL, NULL, NULL     },

    // 12 = HWND_CATUNE_BOTTOM_HALF_RIGHT_ARROW
    { NULL, NULL, NULL     },

    // 13 = HWND_CATUNE_BOTTOM_HALF_UP_ARROW
    { NULL, NULL, NULL     },

    // 14 = HWND_CATUNE_BOTTOM_HALF_DOWN_ARROW
    { NULL, NULL, NULL     },

    // 15 = HWND_CATUNE_BOTTOM_HALF_BG_L
    { _Zui_Catune_Bottom_Half_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // 16 = HWND_CATUNE_BOTTOM_HALF_BG_R
    { _Zui_Catune_Bottom_Half_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // 17 = HWND_CATUNE_PAGE_LIST
    { NULL, NULL, NULL     },

    // 18 = HWND_CATUNE_FREQUENCY
    { NULL, NULL, NULL     },

    // 19 = HWND_CATUNE_FREQUENCY_BG
    { NULL, _Zui_Catune_Frequency_Bg_Focus_DrawStyle, NULL     },

    // 20 = HWND_CATUNE_FREQUENCY_TXT
    { _Zui_Catune_Frequency_Txt_Normal_DrawStyle, _Zui_Catune_Frequency_Txt_Focus_DrawStyle, NULL     },

    // 21 = HWND_CATUNE_FREQUENCY_OPTION
    { _Zui_Catune_Frequency_Option_Normal_DrawStyle, _Zui_Catune_Frequency_Option_Focus_DrawStyle, NULL     },

    // 22 = HWND_CATUNE_SYMBOL
    { NULL, NULL, NULL     },

    // 23 = HWND_CATUNE_SYMBOL_BG
    { NULL, _Zui_Catune_Symbol_Bg_Focus_DrawStyle, NULL     },

    // 24 = HWND_CATUNE_SYMBOL_TXT
    { _Zui_Catune_Symbol_Txt_Normal_DrawStyle, _Zui_Catune_Symbol_Txt_Focus_DrawStyle, NULL     },

    // 25 = HWND_CATUNE_SYMBOL_OPTION
    { _Zui_Catune_Symbol_Option_Normal_DrawStyle, _Zui_Catune_Symbol_Option_Focus_DrawStyle, NULL     },

    // 26 = HWND_CATUNE_QAM_TYPE
    { NULL, NULL, NULL     },

    // 27 = HWND_CATUNE_QAM_TYPE_BG
    { NULL, _Zui_Catune_Qam_Type_Bg_Focus_DrawStyle, NULL     },

    // 28 = HWND_CATUNE_QAM_TYPE_TXT
    { _Zui_Catune_Qam_Type_Txt_Normal_DrawStyle, _Zui_Catune_Qam_Type_Txt_Focus_DrawStyle, NULL     },

    // 29 = HWND_CATUNE_QAM_TYPE_OPTION
    { _Zui_Catune_Qam_Type_Option_Normal_DrawStyle, _Zui_Catune_Qam_Type_Option_Focus_DrawStyle, NULL     },

    // 30 = HWND_CATUNE_SCAN_SIGNAL_BG
    { NULL, NULL, NULL     },

    // 31 = HWND_CATUNE_SCAN_RESULT_NO_SIGNAL_BTN
    { _Zui_Catune_Scan_Result_No_Signal_Btn_Normal_DrawStyle, NULL, NULL     },

    // 32 = HWND_CATUNE_SCAN_RESULT_NO_SIGNAL_TXT
    { _Zui_Catune_Scan_Result_No_Signal_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_No_Signal_Txt_Focus_DrawStyle, NULL     },

    // 33 = HWND_CATUNE_SCAN_RESULT_SEARCHING_TXT
    { _Zui_Catune_Scan_Result_Searching_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Searching_Txt_Focus_DrawStyle, NULL     },

    // 34 = HWND_CATUNE_BAD_TXT
    { _Zui_Catune_Bad_Txt_Normal_DrawStyle, _Zui_Catune_Bad_Txt_Focus_DrawStyle, NULL     },

    // 35 = HWND_CATUNE_NORMAL_TXT
    { _Zui_Catune_Normal_Txt_Normal_DrawStyle, _Zui_Catune_Normal_Txt_Focus_DrawStyle, NULL     },

    // 36 = HWND_CATUNE_GOOD_TXT
    { _Zui_Catune_Good_Txt_Normal_DrawStyle, _Zui_Catune_Good_Txt_Focus_DrawStyle, NULL     },

    // 37 = HWND_CATUNE_SIGNAL_BG
    { NULL, NULL, NULL     },

    // 38 = HWND_CATUNE_SIGNAL_BAR
    { _Zui_Catune_Signal_Bar_Normal_DrawStyle, NULL, NULL     },

    // 39 = HWND_CATUNE_SCAN_ENTERKEY_REMIND_TXT
    { _Zui_Catune_Scan_Enterkey_Remind_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Enterkey_Remind_Txt_Focus_DrawStyle, NULL     },

    // 40 = HWND_CATUNE_SCAN_RESULT
    { NULL, NULL, NULL     },

    // 41 = HWND_CATUNE_SCAN_RESULT_TXT
    { NULL, NULL, NULL     },

    // 42 = HWND_CATUNE_SCAN_RESULT_DTV_TXT
    { _Zui_Catune_Scan_Result_Dtv_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Dtv_Txt_Focus_DrawStyle, NULL     },

    // 43 = HWND_CATUNE_SCAN_RESULT_DTV_NUMBER_TXT
    { _Zui_Catune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Dtv_Number_Txt_Focus_DrawStyle, NULL     },

    // 44 = HWND_CATUNE_SCAN_RESULT_RADIO_TXT
    { _Zui_Catune_Scan_Result_Radio_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Radio_Txt_Focus_DrawStyle, NULL     },

    // 45 = HWND_CATUNE_SCAN_RESULT_RADIO_NUMBER_TXT
    { _Zui_Catune_Scan_Result_Radio_Number_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Radio_Number_Txt_Focus_DrawStyle, NULL     },

    // 46 = HWND_CATUNE_SCAN_RESULT_DATA_TXT
    { _Zui_Catune_Scan_Result_Data_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Data_Txt_Focus_DrawStyle, NULL     },

    // 47 = HWND_CATUNE_SCAN_RESULT_DATA_NUMBER_TXT
    { _Zui_Catune_Scan_Result_Data_Number_Txt_Normal_DrawStyle, _Zui_Catune_Scan_Result_Data_Number_Txt_Focus_DrawStyle, NULL     },

    // 48 = HWND_MENU_DLG_DVB_SCAN_PAGE
    { NULL, NULL, NULL     },

    // 49 = HWND_MENU_DLG_DVB_SCAN_MENU_BG_C
    { _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_C_Normal_DrawStyle, _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_C_Focus_DrawStyle, NULL     },

    // 50 = HWND_MENU_DLG_DVB_SCAN_MENU_BG_L
    { _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_L_Normal_DrawStyle, _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_L_Focus_DrawStyle, NULL     },

    // 51 = HWND_MENU_DLG_DVB_SCAN_MENU_BG_R
    { _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_R_Normal_DrawStyle, _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_R_Focus_DrawStyle, NULL     },

    // 52 = HWND_MENU_DLG_DVB_SCAN_MENU_BG_V
    { _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_V_Normal_DrawStyle, _Zui_Menu_Dlg_Dvb_Scan_Menu_Bg_V_Focus_DrawStyle, NULL     },

    // 53 = HWND_MENU_DLG_DVB_SCAN_TYPE_TEXT
    { _Zui_Menu_Dlg_Dvb_Scan_Type_Text_Normal_DrawStyle, _Zui_Menu_Dlg_Dvb_Scan_Type_Text_Focus_DrawStyle, NULL     },

    // 54 = HWND_MENU_DVBC_SCAN_OK_BTN
    { NULL, NULL, NULL     },

    // 55 = HWND_MENU_DVBC_SCAN_MENU_BTN
    { NULL, NULL, NULL     },

    // 56 = HWND_DVBCSCAN_SCAN_TYPE_BG
    { NULL, _Zui_Dvbcscan_Scan_Type_Bg_Focus_DrawStyle, NULL     },

    // 57 = HWND_MENU_DLG_DVBC_SCAN_TYPE_TEXT
    { _Zui_Menu_Dlg_Dvbc_Scan_Type_Text_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Type_Text_Focus_DrawStyle, NULL     },

    // 58 = HWND_MENU_DLG_DVBC_SCAN_TYPE_OPTION
    { _Zui_Menu_Dlg_Dvbc_Scan_Type_Option_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Type_Option_Focus_DrawStyle, NULL     },

    // 59 = HWND_DVBCSCAN_FREQUENCY_BG
    { NULL, _Zui_Dvbcscan_Frequency_Bg_Focus_DrawStyle, NULL     },

    // 60 = HWND_MENU_DLG_DVBC_FREQUENCY_TEXT
    { _Zui_Menu_Dlg_Dvbc_Frequency_Text_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Frequency_Text_Focus_DrawStyle, _Zui_Menu_Dlg_Dvbc_Frequency_Text_Disabled_DrawStyle     },

    // 61 = HWND_MENU_DLG_DVBC_SCAN_FREQUENCY_OPTION
    { _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Focus_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Frequency_Option_Disabled_DrawStyle     },

    // 62 = HWND_DVBCSCAN_NETWORKID_BG
    { NULL, _Zui_Dvbcscan_Networkid_Bg_Focus_DrawStyle, NULL     },

    // 63 = HWND_MENU_DLG_DVBC_NETWORKID_TEXT
    { _Zui_Menu_Dlg_Dvbc_Networkid_Text_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Networkid_Text_Focus_DrawStyle, _Zui_Menu_Dlg_Dvbc_Networkid_Text_Disabled_DrawStyle     },

    // 64 = HWND_MENU_DLG_DVBC_SCAN_NETWORKID_OPTION
    { _Zui_Menu_Dlg_Dvbc_Scan_Networkid_Option_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Networkid_Option_Focus_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Networkid_Option_Disabled_DrawStyle     },

    // 65 = HWND_DVBCSCAN_SYMBOL_RATE_BG
    { NULL, _Zui_Dvbcscan_Symbol_Rate_Bg_Focus_DrawStyle, NULL     },

    // 66 = HWND_MENU_DLG_DVBC_SYMBOL_RATE_TEXT
    { _Zui_Menu_Dlg_Dvbc_Symbol_Rate_Text_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Symbol_Rate_Text_Focus_DrawStyle, _Zui_Menu_Dlg_Dvbc_Symbol_Rate_Text_Disabled_DrawStyle     },

    // 67 = HWND_MENU_DLG_DVBC_SCAN_SYMBOL_RATE_OPTION
    { _Zui_Menu_Dlg_Dvbc_Scan_Symbol_Rate_Option_Normal_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Symbol_Rate_Option_Focus_DrawStyle, _Zui_Menu_Dlg_Dvbc_Scan_Symbol_Rate_Option_Disabled_DrawStyle     },

};
