////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// SUBLANG_BG_PANE styles..


/////////////////////////////////////////////////////
// SUBLANG_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_87 },
    { CP_NOON, 0 },
};
#define _Zui_Sublang_Bg_C_Focus_DrawStyle _Zui_Sublang_Bg_C_Normal_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_86 },
    { CP_NOON, 0 },
};
#define _Zui_Sublang_Bg_L_Focus_DrawStyle _Zui_Sublang_Bg_L_Normal_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_88 },
    { CP_NOON, 0 },
};
#define _Zui_Sublang_Bg_R_Focus_DrawStyle _Zui_Sublang_Bg_R_Normal_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_TOP_HALF_BANNER_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Top_Half_Banner_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_923 },
    { CP_NOON, 0 },
};
#define _Zui_Sublang_Top_Half_Banner_Title_Focus_DrawStyle _Zui_Sublang_Top_Half_Banner_Title_Normal_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_BOTTOM_HALF_OK_BTN styles..


/////////////////////////////////////////////////////
// SUBLANG_LIST_PANE styles..


/////////////////////////////////////////////////////
// SUBLANG_ITEM0 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_124 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_TTX styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_195 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_196 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_HOH styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_197 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_198 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_659 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_924 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_HD styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_199 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_200 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_0 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_125 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// SUBLANG_ITEM1 styles..

#define _Zui_Sublang_Item1_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM1_ICON_TTX styles..

#define _Zui_Sublang_Item1_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item1_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM1_ICON_HOH styles..

#define _Zui_Sublang_Item1_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item1_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM1_TEXT styles..

#define _Zui_Sublang_Item1_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item1_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM1_ICON_HD styles..

#define _Zui_Sublang_Item1_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item1_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_1 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_1_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM2 styles..

#define _Zui_Sublang_Item2_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM2_ICON_TTX styles..

#define _Zui_Sublang_Item2_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item2_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM2_ICON_HOH styles..

#define _Zui_Sublang_Item2_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item2_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM2_TEXT styles..

#define _Zui_Sublang_Item2_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item2_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM2_ICON_HD styles..

#define _Zui_Sublang_Item2_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item2_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_2 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_2_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM3 styles..

#define _Zui_Sublang_Item3_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM3_ICON_TTX styles..

#define _Zui_Sublang_Item3_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item3_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM3_ICON_HOH styles..

#define _Zui_Sublang_Item3_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item3_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM3_TEXT styles..

#define _Zui_Sublang_Item3_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item3_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM3_ICON_HD styles..

#define _Zui_Sublang_Item3_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item3_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_3 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_3_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM4 styles..

#define _Zui_Sublang_Item4_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM4_ICON_TTX styles..

#define _Zui_Sublang_Item4_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item4_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM4_ICON_HOH styles..

#define _Zui_Sublang_Item4_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item4_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM4_TEXT styles..

#define _Zui_Sublang_Item4_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item4_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM4_ICON_HD styles..

#define _Zui_Sublang_Item4_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item4_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_4 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_4_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM5 styles..

#define _Zui_Sublang_Item5_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM5_ICON_TTX styles..

#define _Zui_Sublang_Item5_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item5_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM5_ICON_HOH styles..

#define _Zui_Sublang_Item5_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item5_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM5_TEXT styles..

#define _Zui_Sublang_Item5_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item5_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM5_ICON_HD styles..

#define _Zui_Sublang_Item5_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item5_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_5 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_5_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM6 styles..

#define _Zui_Sublang_Item6_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM6_ICON_TTX styles..

#define _Zui_Sublang_Item6_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item6_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM6_ICON_HOH styles..

#define _Zui_Sublang_Item6_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item6_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM6_TEXT styles..

#define _Zui_Sublang_Item6_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item6_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM6_ICON_HD styles..

#define _Zui_Sublang_Item6_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item6_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_6 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_6_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM7 styles..

#define _Zui_Sublang_Item7_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM7_ICON_TTX styles..

#define _Zui_Sublang_Item7_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item7_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM7_ICON_HOH styles..

#define _Zui_Sublang_Item7_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item7_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM7_TEXT styles..

#define _Zui_Sublang_Item7_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item7_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM7_ICON_HD styles..

#define _Zui_Sublang_Item7_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item7_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_7 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_7_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM8 styles..

#define _Zui_Sublang_Item8_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM8_ICON_TTX styles..

#define _Zui_Sublang_Item8_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item8_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM8_ICON_HOH styles..

#define _Zui_Sublang_Item8_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item8_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM8_TEXT styles..

#define _Zui_Sublang_Item8_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item8_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM8_ICON_HD styles..

#define _Zui_Sublang_Item8_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item8_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_8 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_8_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM9 styles..

#define _Zui_Sublang_Item9_Focus_DrawStyle _Zui_Sublang_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM9_ICON_TTX styles..

#define _Zui_Sublang_Item9_Icon_Ttx_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle
#define _Zui_Sublang_Item9_Icon_Ttx_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM9_ICON_HOH styles..

#define _Zui_Sublang_Item9_Icon_Hoh_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle
#define _Zui_Sublang_Item9_Icon_Hoh_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM9_TEXT styles..

#define _Zui_Sublang_Item9_Text_Normal_DrawStyle _Zui_Sublang_Item0_Text_Normal_DrawStyle
#define _Zui_Sublang_Item9_Text_Focus_DrawStyle _Zui_Sublang_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM9_ICON_HD styles..

#define _Zui_Sublang_Item9_Icon_Hd_Normal_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle
#define _Zui_Sublang_Item9_Icon_Hd_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle

/////////////////////////////////////////////////////
// SUBLANG_ITEM0_ICON_UPDOWN_ARROW_9 styles..

#define _Zui_Sublang_Item0_Icon_Updown_Arrow_9_Focus_DrawStyle _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Subtitle_Language[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_SUBLANG_BG_PANE
    { NULL, NULL, NULL     },

    // 2 = HWND_SUBLANG_BG_C
    { _Zui_Sublang_Bg_C_Normal_DrawStyle, _Zui_Sublang_Bg_C_Focus_DrawStyle, NULL     },

    // 3 = HWND_SUBLANG_BG_L
    { _Zui_Sublang_Bg_L_Normal_DrawStyle, _Zui_Sublang_Bg_L_Focus_DrawStyle, NULL     },

    // 4 = HWND_SUBLANG_BG_R
    { _Zui_Sublang_Bg_R_Normal_DrawStyle, _Zui_Sublang_Bg_R_Focus_DrawStyle, NULL     },

    // 5 = HWND_SUBLANG_TOP_HALF_BANNER_TITLE
    { _Zui_Sublang_Top_Half_Banner_Title_Normal_DrawStyle, _Zui_Sublang_Top_Half_Banner_Title_Focus_DrawStyle, NULL     },

    // 6 = HWND_SUBLANG_BOTTOM_HALF_OK_BTN
    { NULL, NULL, NULL     },

    // 7 = HWND_SUBLANG_LIST_PANE
    { NULL, NULL, NULL     },

    // 8 = HWND_SUBLANG_ITEM0
    { NULL, _Zui_Sublang_Item0_Focus_DrawStyle, NULL     },

    // 9 = HWND_SUBLANG_ITEM0_ICON_TTX
    { _Zui_Sublang_Item0_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item0_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 10 = HWND_SUBLANG_ITEM0_ICON_HOH
    { _Zui_Sublang_Item0_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item0_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 11 = HWND_SUBLANG_ITEM0_TEXT
    { _Zui_Sublang_Item0_Text_Normal_DrawStyle, _Zui_Sublang_Item0_Text_Focus_DrawStyle, NULL     },

    // 12 = HWND_SUBLANG_ITEM0_ICON_HD
    { _Zui_Sublang_Item0_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item0_Icon_Hd_Focus_DrawStyle, NULL     },

    // 13 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_0
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_0_Focus_DrawStyle, NULL     },

    // 14 = HWND_SUBLANG_ITEM1
    { NULL, _Zui_Sublang_Item1_Focus_DrawStyle, NULL     },

    // 15 = HWND_SUBLANG_ITEM1_ICON_TTX
    { _Zui_Sublang_Item1_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item1_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 16 = HWND_SUBLANG_ITEM1_ICON_HOH
    { _Zui_Sublang_Item1_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item1_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 17 = HWND_SUBLANG_ITEM1_TEXT
    { _Zui_Sublang_Item1_Text_Normal_DrawStyle, _Zui_Sublang_Item1_Text_Focus_DrawStyle, NULL     },

    // 18 = HWND_SUBLANG_ITEM1_ICON_HD
    { _Zui_Sublang_Item1_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item1_Icon_Hd_Focus_DrawStyle, NULL     },

    // 19 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_1
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_1_Focus_DrawStyle, NULL     },

    // 20 = HWND_SUBLANG_ITEM2
    { NULL, _Zui_Sublang_Item2_Focus_DrawStyle, NULL     },

    // 21 = HWND_SUBLANG_ITEM2_ICON_TTX
    { _Zui_Sublang_Item2_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item2_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 22 = HWND_SUBLANG_ITEM2_ICON_HOH
    { _Zui_Sublang_Item2_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item2_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 23 = HWND_SUBLANG_ITEM2_TEXT
    { _Zui_Sublang_Item2_Text_Normal_DrawStyle, _Zui_Sublang_Item2_Text_Focus_DrawStyle, NULL     },

    // 24 = HWND_SUBLANG_ITEM2_ICON_HD
    { _Zui_Sublang_Item2_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item2_Icon_Hd_Focus_DrawStyle, NULL     },

    // 25 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_2
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_2_Focus_DrawStyle, NULL     },

    // 26 = HWND_SUBLANG_ITEM3
    { NULL, _Zui_Sublang_Item3_Focus_DrawStyle, NULL     },

    // 27 = HWND_SUBLANG_ITEM3_ICON_TTX
    { _Zui_Sublang_Item3_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item3_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 28 = HWND_SUBLANG_ITEM3_ICON_HOH
    { _Zui_Sublang_Item3_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item3_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 29 = HWND_SUBLANG_ITEM3_TEXT
    { _Zui_Sublang_Item3_Text_Normal_DrawStyle, _Zui_Sublang_Item3_Text_Focus_DrawStyle, NULL     },

    // 30 = HWND_SUBLANG_ITEM3_ICON_HD
    { _Zui_Sublang_Item3_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item3_Icon_Hd_Focus_DrawStyle, NULL     },

    // 31 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_3
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_3_Focus_DrawStyle, NULL     },

    // 32 = HWND_SUBLANG_ITEM4
    { NULL, _Zui_Sublang_Item4_Focus_DrawStyle, NULL     },

    // 33 = HWND_SUBLANG_ITEM4_ICON_TTX
    { _Zui_Sublang_Item4_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item4_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 34 = HWND_SUBLANG_ITEM4_ICON_HOH
    { _Zui_Sublang_Item4_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item4_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 35 = HWND_SUBLANG_ITEM4_TEXT
    { _Zui_Sublang_Item4_Text_Normal_DrawStyle, _Zui_Sublang_Item4_Text_Focus_DrawStyle, NULL     },

    // 36 = HWND_SUBLANG_ITEM4_ICON_HD
    { _Zui_Sublang_Item4_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item4_Icon_Hd_Focus_DrawStyle, NULL     },

    // 37 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_4
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_4_Focus_DrawStyle, NULL     },

    // 38 = HWND_SUBLANG_ITEM5
    { NULL, _Zui_Sublang_Item5_Focus_DrawStyle, NULL     },

    // 39 = HWND_SUBLANG_ITEM5_ICON_TTX
    { _Zui_Sublang_Item5_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item5_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 40 = HWND_SUBLANG_ITEM5_ICON_HOH
    { _Zui_Sublang_Item5_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item5_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 41 = HWND_SUBLANG_ITEM5_TEXT
    { _Zui_Sublang_Item5_Text_Normal_DrawStyle, _Zui_Sublang_Item5_Text_Focus_DrawStyle, NULL     },

    // 42 = HWND_SUBLANG_ITEM5_ICON_HD
    { _Zui_Sublang_Item5_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item5_Icon_Hd_Focus_DrawStyle, NULL     },

    // 43 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_5
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_5_Focus_DrawStyle, NULL     },

    // 44 = HWND_SUBLANG_ITEM6
    { NULL, _Zui_Sublang_Item6_Focus_DrawStyle, NULL     },

    // 45 = HWND_SUBLANG_ITEM6_ICON_TTX
    { _Zui_Sublang_Item6_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item6_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 46 = HWND_SUBLANG_ITEM6_ICON_HOH
    { _Zui_Sublang_Item6_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item6_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 47 = HWND_SUBLANG_ITEM6_TEXT
    { _Zui_Sublang_Item6_Text_Normal_DrawStyle, _Zui_Sublang_Item6_Text_Focus_DrawStyle, NULL     },

    // 48 = HWND_SUBLANG_ITEM6_ICON_HD
    { _Zui_Sublang_Item6_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item6_Icon_Hd_Focus_DrawStyle, NULL     },

    // 49 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_6
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_6_Focus_DrawStyle, NULL     },

    // 50 = HWND_SUBLANG_ITEM7
    { NULL, _Zui_Sublang_Item7_Focus_DrawStyle, NULL     },

    // 51 = HWND_SUBLANG_ITEM7_ICON_TTX
    { _Zui_Sublang_Item7_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item7_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 52 = HWND_SUBLANG_ITEM7_ICON_HOH
    { _Zui_Sublang_Item7_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item7_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 53 = HWND_SUBLANG_ITEM7_TEXT
    { _Zui_Sublang_Item7_Text_Normal_DrawStyle, _Zui_Sublang_Item7_Text_Focus_DrawStyle, NULL     },

    // 54 = HWND_SUBLANG_ITEM7_ICON_HD
    { _Zui_Sublang_Item7_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item7_Icon_Hd_Focus_DrawStyle, NULL     },

    // 55 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_7
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_7_Focus_DrawStyle, NULL     },

    // 56 = HWND_SUBLANG_ITEM8
    { NULL, _Zui_Sublang_Item8_Focus_DrawStyle, NULL     },

    // 57 = HWND_SUBLANG_ITEM8_ICON_TTX
    { _Zui_Sublang_Item8_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item8_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 58 = HWND_SUBLANG_ITEM8_ICON_HOH
    { _Zui_Sublang_Item8_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item8_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 59 = HWND_SUBLANG_ITEM8_TEXT
    { _Zui_Sublang_Item8_Text_Normal_DrawStyle, _Zui_Sublang_Item8_Text_Focus_DrawStyle, NULL     },

    // 60 = HWND_SUBLANG_ITEM8_ICON_HD
    { _Zui_Sublang_Item8_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item8_Icon_Hd_Focus_DrawStyle, NULL     },

    // 61 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_8
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_8_Focus_DrawStyle, NULL     },

    // 62 = HWND_SUBLANG_ITEM9
    { NULL, _Zui_Sublang_Item9_Focus_DrawStyle, NULL     },

    // 63 = HWND_SUBLANG_ITEM9_ICON_TTX
    { _Zui_Sublang_Item9_Icon_Ttx_Normal_DrawStyle, _Zui_Sublang_Item9_Icon_Ttx_Focus_DrawStyle, NULL     },

    // 64 = HWND_SUBLANG_ITEM9_ICON_HOH
    { _Zui_Sublang_Item9_Icon_Hoh_Normal_DrawStyle, _Zui_Sublang_Item9_Icon_Hoh_Focus_DrawStyle, NULL     },

    // 65 = HWND_SUBLANG_ITEM9_TEXT
    { _Zui_Sublang_Item9_Text_Normal_DrawStyle, _Zui_Sublang_Item9_Text_Focus_DrawStyle, NULL     },

    // 66 = HWND_SUBLANG_ITEM9_ICON_HD
    { _Zui_Sublang_Item9_Icon_Hd_Normal_DrawStyle, _Zui_Sublang_Item9_Icon_Hd_Focus_DrawStyle, NULL     },

    // 67 = HWND_SUBLANG_ITEM0_ICON_UPDOWN_ARROW_9
    { NULL, _Zui_Sublang_Item0_Icon_Updown_Arrow_9_Focus_DrawStyle, NULL     },

};
