////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// DTUNE_BG_PANE styles..


/////////////////////////////////////////////////////
// DTUNE_BG_PANE_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_162 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_BG_PANE_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_163 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_BG_PANE_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_164 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_TITLE_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Title_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_772 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Title_Txt_Focus_DrawStyle _Zui_Dtune_Title_Txt_Normal_DrawStyle
#define _Zui_Dtune_Title_Txt_Disabled_DrawStyle _Zui_Dtune_Title_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_BG_PANE_LEFT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_Left_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_34 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Bg_Pane_Left_Arrow_Focus_DrawStyle _Zui_Dtune_Bg_Pane_Left_Arrow_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_BG_PANE_RIGHT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_Right_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_35 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Bg_Pane_Right_Arrow_Focus_DrawStyle _Zui_Dtune_Bg_Pane_Right_Arrow_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_BG_PANE_INC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_Inc_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_160 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_BG_PANE_DEC styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bg_Pane_Dec_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_165 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_MANUAL_SCAN_BAR styles..


/////////////////////////////////////////////////////
// DTUNE_MANUAL_SCAN_UFH_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Manual_Scan_Ufh_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_773 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Manual_Scan_Ufh_Txt_Focus_DrawStyle _Zui_Dtune_Manual_Scan_Ufh_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_MANUAL_SCAN_CHANNEL_NAME_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Manual_Scan_Channel_Name_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_774 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Manual_Scan_Channel_Name_Txt_Focus_DrawStyle _Zui_Dtune_Manual_Scan_Channel_Name_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT styles..


/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_TXT styles..


/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_DTV_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_Dtv_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_487 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Result_Dtv_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Dtv_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_DTV_NUMBER_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_426 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_RADIO_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_Radio_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_775 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Result_Radio_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Radio_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_RADIO_NUMBER_TXT styles..

#define _Zui_Dtune_Scan_Result_Radio_Number_Txt_Normal_DrawStyle _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle
#define _Zui_Dtune_Scan_Result_Radio_Number_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_DATA_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_Data_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_776 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Result_Data_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Data_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_DATA_NUMBER_TXT styles..

#define _Zui_Dtune_Scan_Result_Data_Number_Txt_Normal_DrawStyle _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle
#define _Zui_Dtune_Scan_Result_Data_Number_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_SIGNAL_BG styles..


/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_NO_SIGNAL_BTN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_No_Signal_Btn_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_15 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_NO_SIGNAL_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_No_Signal_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_777 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Result_No_Signal_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_No_Signal_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SCAN_RESULT_SEARCHING_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Result_Searching_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_778 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Result_Searching_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Result_Searching_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_BAD_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Bad_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_779 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Bad_Txt_Focus_DrawStyle _Zui_Dtune_Bad_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_NORMAL_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Normal_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_780 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Normal_Txt_Focus_DrawStyle _Zui_Dtune_Normal_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_GOOD_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Good_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_781 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Good_Txt_Focus_DrawStyle _Zui_Dtune_Good_Txt_Normal_DrawStyle

/////////////////////////////////////////////////////
// DTUNE_SIGNAL_BG styles..


/////////////////////////////////////////////////////
// DTUNE_SIGNAL_BAR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Signal_Bar_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DTUNE_SCAN_ENTERKEY_REMIND_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Dtune_Scan_Enterkey_Remind_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_782 },
    { CP_NOON, 0 },
};
#define _Zui_Dtune_Scan_Enterkey_Remind_Txt_Focus_DrawStyle _Zui_Dtune_Scan_Enterkey_Remind_Txt_Normal_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Dtv_Manual_Tuning[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_DTUNE_BG_PANE
    { NULL, NULL, NULL     },

    // 2 = HWND_DTUNE_BG_PANE_L
    { _Zui_Dtune_Bg_Pane_L_Normal_DrawStyle, NULL, NULL     },

    // 3 = HWND_DTUNE_BG_PANE_C
    { _Zui_Dtune_Bg_Pane_C_Normal_DrawStyle, NULL, NULL     },

    // 4 = HWND_DTUNE_BG_PANE_R
    { _Zui_Dtune_Bg_Pane_R_Normal_DrawStyle, NULL, NULL     },

    // 5 = HWND_DTUNE_TITLE_TXT
    { _Zui_Dtune_Title_Txt_Normal_DrawStyle, _Zui_Dtune_Title_Txt_Focus_DrawStyle, _Zui_Dtune_Title_Txt_Disabled_DrawStyle     },

    // 6 = HWND_DTUNE_BG_PANE_LEFT_ARROW
    { _Zui_Dtune_Bg_Pane_Left_Arrow_Normal_DrawStyle, _Zui_Dtune_Bg_Pane_Left_Arrow_Focus_DrawStyle, NULL     },

    // 7 = HWND_DTUNE_BG_PANE_RIGHT_ARROW
    { _Zui_Dtune_Bg_Pane_Right_Arrow_Normal_DrawStyle, _Zui_Dtune_Bg_Pane_Right_Arrow_Focus_DrawStyle, NULL     },

    // 8 = HWND_DTUNE_BG_PANE_INC
    { _Zui_Dtune_Bg_Pane_Inc_Normal_DrawStyle, NULL, NULL     },

    // 9 = HWND_DTUNE_BG_PANE_DEC
    { _Zui_Dtune_Bg_Pane_Dec_Normal_DrawStyle, NULL, NULL     },

    // 10 = HWND_DTUNE_MANUAL_SCAN_BAR
    { NULL, NULL, NULL     },

    // 11 = HWND_DTUNE_MANUAL_SCAN_UFH_TXT
    { _Zui_Dtune_Manual_Scan_Ufh_Txt_Normal_DrawStyle, _Zui_Dtune_Manual_Scan_Ufh_Txt_Focus_DrawStyle, NULL     },

    // 12 = HWND_DTUNE_MANUAL_SCAN_CHANNEL_NAME_TXT
    { _Zui_Dtune_Manual_Scan_Channel_Name_Txt_Normal_DrawStyle, _Zui_Dtune_Manual_Scan_Channel_Name_Txt_Focus_DrawStyle, NULL     },

    // 13 = HWND_DTUNE_SCAN_RESULT
    { NULL, NULL, NULL     },

    // 14 = HWND_DTUNE_SCAN_RESULT_TXT
    { NULL, NULL, NULL     },

    // 15 = HWND_DTUNE_SCAN_RESULT_DTV_TXT
    { _Zui_Dtune_Scan_Result_Dtv_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Dtv_Txt_Focus_DrawStyle, NULL     },

    // 16 = HWND_DTUNE_SCAN_RESULT_DTV_NUMBER_TXT
    { _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Dtv_Number_Txt_Focus_DrawStyle, NULL     },

    // 17 = HWND_DTUNE_SCAN_RESULT_RADIO_TXT
    { _Zui_Dtune_Scan_Result_Radio_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Radio_Txt_Focus_DrawStyle, NULL     },

    // 18 = HWND_DTUNE_SCAN_RESULT_RADIO_NUMBER_TXT
    { _Zui_Dtune_Scan_Result_Radio_Number_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Radio_Number_Txt_Focus_DrawStyle, NULL     },

    // 19 = HWND_DTUNE_SCAN_RESULT_DATA_TXT
    { _Zui_Dtune_Scan_Result_Data_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Data_Txt_Focus_DrawStyle, NULL     },

    // 20 = HWND_DTUNE_SCAN_RESULT_DATA_NUMBER_TXT
    { _Zui_Dtune_Scan_Result_Data_Number_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Data_Number_Txt_Focus_DrawStyle, NULL     },

    // 21 = HWND_DTUNE_SCAN_SIGNAL_BG
    { NULL, NULL, NULL     },

    // 22 = HWND_DTUNE_SCAN_RESULT_NO_SIGNAL_BTN
    { _Zui_Dtune_Scan_Result_No_Signal_Btn_Normal_DrawStyle, NULL, NULL     },

    // 23 = HWND_DTUNE_SCAN_RESULT_NO_SIGNAL_TXT
    { _Zui_Dtune_Scan_Result_No_Signal_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_No_Signal_Txt_Focus_DrawStyle, NULL     },

    // 24 = HWND_DTUNE_SCAN_RESULT_SEARCHING_TXT
    { _Zui_Dtune_Scan_Result_Searching_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Result_Searching_Txt_Focus_DrawStyle, NULL     },

    // 25 = HWND_DTUNE_BAD_TXT
    { _Zui_Dtune_Bad_Txt_Normal_DrawStyle, _Zui_Dtune_Bad_Txt_Focus_DrawStyle, NULL     },

    // 26 = HWND_DTUNE_NORMAL_TXT
    { _Zui_Dtune_Normal_Txt_Normal_DrawStyle, _Zui_Dtune_Normal_Txt_Focus_DrawStyle, NULL     },

    // 27 = HWND_DTUNE_GOOD_TXT
    { _Zui_Dtune_Good_Txt_Normal_DrawStyle, _Zui_Dtune_Good_Txt_Focus_DrawStyle, NULL     },

    // 28 = HWND_DTUNE_SIGNAL_BG
    { NULL, NULL, NULL     },

    // 29 = HWND_DTUNE_SIGNAL_BAR
    { _Zui_Dtune_Signal_Bar_Normal_DrawStyle, NULL, NULL     },

    // 30 = HWND_DTUNE_SCAN_ENTERKEY_REMIND_TXT
    { _Zui_Dtune_Scan_Enterkey_Remind_Txt_Normal_DrawStyle, _Zui_Dtune_Scan_Enterkey_Remind_Txt_Focus_DrawStyle, NULL     },

};
