////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// EFFECT_BACKGROUND styles..


/////////////////////////////////////////////////////
// EFFECT_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_28 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_29 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_30 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_BAR styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_EXIT_BG styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_EXIT_TXT styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_OK_BG styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_OK_TXT styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_UP_ARROW styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_LEFT_ARROW styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_RIGHT_ARROW styles..


/////////////////////////////////////////////////////
// EFFECT_BOTTOM_HALF_DOWN_ARROW styles..


/////////////////////////////////////////////////////
// EFFECT_TOP_HALF_BG styles..


/////////////////////////////////////////////////////
// EFFECT_TOP_ICON_OPTION styles..


/////////////////////////////////////////////////////
// EFFECT_RIGHT_TOP_ICON styles..


/////////////////////////////////////////////////////
// EFFECT_SETTING_MAIN styles..


/////////////////////////////////////////////////////
// EFFECT_MAIN_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Title_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_27 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1199 },
    { CP_NOON, 0 },
};
#define _Zui_Effect_Main_Title_Focus_DrawStyle _Zui_Effect_Main_Title_Normal_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Title_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1200 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_PAGE_LIST styles..


/////////////////////////////////////////////////////
// EFFECT_MAIN_PAGE styles..


/////////////////////////////////////////////////////
// EFFECT_MAIN_PAGE_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Page_Bg_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_33 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_PAGE_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Page_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1201 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Page_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1202 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Page_Text_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1203 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_PAGE_OPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Page_Option_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1204 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Page_Option_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1205 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_OPEN styles..


/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_OPEN_BG styles..

#define _Zui_Effect_Main_Menu_Open_Bg_Focus_DrawStyle _Zui_Effect_Main_Page_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_OPEN_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Open_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1206 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Open_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1207 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_OPEN_OPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Open_Option_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_487 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Open_Option_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1208 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Open_Option_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1209 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_CLOSE styles..


/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_CLOSE_BG styles..

#define _Zui_Effect_Main_Menu_Close_Bg_Focus_DrawStyle _Zui_Effect_Main_Page_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_CLOSE_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Close_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1210 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Close_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1211 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Close_Text_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1212 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_CLOSE_OPTION styles..

#define _Zui_Effect_Main_Menu_Close_Option_Normal_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Normal_DrawStyle
#define _Zui_Effect_Main_Menu_Close_Option_Focus_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_ITEM styles..


/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_ITEM_BG styles..

#define _Zui_Effect_Main_Menu_Item_Bg_Focus_DrawStyle _Zui_Effect_Main_Page_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_ITEM_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Item_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1213 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Main_Menu_Item_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1214 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_MAIN_MENU_ITEM_OPTION styles..

#define _Zui_Effect_Main_Menu_Item_Option_Normal_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Normal_DrawStyle
#define _Zui_Effect_Main_Menu_Item_Option_Focus_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_POPUP_DIALOG styles..


/////////////////////////////////////////////////////
// EFFECT_POPUP_DIALOG_BG styles..

#define _Zui_Effect_Popup_Dialog_Bg_Focus_DrawStyle _Zui_Effect_Main_Page_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_POPUP_DIALOG_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Popup_Dialog_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1215 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Popup_Dialog_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1216 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_POPUP_DIALOG_OPTION styles..

#define _Zui_Effect_Popup_Dialog_Option_Normal_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Normal_DrawStyle
#define _Zui_Effect_Popup_Dialog_Option_Focus_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_INPUT_SOURCE styles..


/////////////////////////////////////////////////////
// EFFECT_INPUT_SOURCE_BG styles..

#define _Zui_Effect_Input_Source_Bg_Focus_DrawStyle _Zui_Effect_Main_Page_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// EFFECT_INPUT_SOURCE_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Input_Source_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1217 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Effect_Input_Source_Txt_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1218 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EFFECT_INPUT_SOURCE_OPTION styles..

#define _Zui_Effect_Input_Source_Option_Normal_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Normal_DrawStyle
#define _Zui_Effect_Input_Source_Option_Focus_DrawStyle _Zui_Effect_Main_Menu_Open_Option_Focus_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Effect_Setting[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_EFFECT_BACKGROUND
    { NULL, NULL, NULL     },

    // 2 = HWND_EFFECT_BG_L
    { _Zui_Effect_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // 3 = HWND_EFFECT_BG_C
    { _Zui_Effect_Bg_C_Normal_DrawStyle, NULL, NULL     },

    // 4 = HWND_EFFECT_BG_R
    { _Zui_Effect_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // 5 = HWND_EFFECT_BOTTOM_HALF_BAR
    { NULL, NULL, NULL     },

    // 6 = HWND_EFFECT_BOTTOM_HALF_EXIT_BG
    { NULL, NULL, NULL     },

    // 7 = HWND_EFFECT_BOTTOM_HALF_EXIT_TXT
    { NULL, NULL, NULL     },

    // 8 = HWND_EFFECT_BOTTOM_HALF_OK_BG
    { NULL, NULL, NULL     },

    // 9 = HWND_EFFECT_BOTTOM_HALF_OK_TXT
    { NULL, NULL, NULL     },

    // 10 = HWND_EFFECT_BOTTOM_HALF_UP_ARROW
    { NULL, NULL, NULL     },

    // 11 = HWND_EFFECT_BOTTOM_HALF_LEFT_ARROW
    { NULL, NULL, NULL     },

    // 12 = HWND_EFFECT_BOTTOM_HALF_RIGHT_ARROW
    { NULL, NULL, NULL     },

    // 13 = HWND_EFFECT_BOTTOM_HALF_DOWN_ARROW
    { NULL, NULL, NULL     },

    // 14 = HWND_EFFECT_TOP_HALF_BG
    { NULL, NULL, NULL     },

    // 15 = HWND_EFFECT_TOP_ICON_OPTION
    { NULL, NULL, NULL     },

    // 16 = HWND_EFFECT_RIGHT_TOP_ICON
    { NULL, NULL, NULL     },

    // 17 = HWND_EFFECT_SETTING_MAIN
    { NULL, NULL, NULL     },

    // 18 = HWND_EFFECT_MAIN_TITLE
    { _Zui_Effect_Main_Title_Normal_DrawStyle, _Zui_Effect_Main_Title_Focus_DrawStyle, _Zui_Effect_Main_Title_Disabled_DrawStyle     },

    // 19 = HWND_EFFECT_MAIN_PAGE_LIST
    { NULL, NULL, NULL     },

    // 20 = HWND_EFFECT_MAIN_PAGE
    { NULL, NULL, NULL     },

    // 21 = HWND_EFFECT_MAIN_PAGE_BG
    { NULL, _Zui_Effect_Main_Page_Bg_Focus_DrawStyle, NULL     },

    // 22 = HWND_EFFECT_MAIN_PAGE_TEXT
    { _Zui_Effect_Main_Page_Text_Normal_DrawStyle, _Zui_Effect_Main_Page_Text_Focus_DrawStyle, _Zui_Effect_Main_Page_Text_Disabled_DrawStyle     },

    // 23 = HWND_EFFECT_MAIN_PAGE_OPTION
    { _Zui_Effect_Main_Page_Option_Normal_DrawStyle, _Zui_Effect_Main_Page_Option_Focus_DrawStyle, NULL     },

    // 24 = HWND_EFFECT_MAIN_MENU_OPEN
    { NULL, NULL, NULL     },

    // 25 = HWND_EFFECT_MAIN_MENU_OPEN_BG
    { NULL, _Zui_Effect_Main_Menu_Open_Bg_Focus_DrawStyle, NULL     },

    // 26 = HWND_EFFECT_MAIN_MENU_OPEN_TEXT
    { _Zui_Effect_Main_Menu_Open_Text_Normal_DrawStyle, _Zui_Effect_Main_Menu_Open_Text_Focus_DrawStyle, NULL     },

    // 27 = HWND_EFFECT_MAIN_MENU_OPEN_OPTION
    { _Zui_Effect_Main_Menu_Open_Option_Normal_DrawStyle, _Zui_Effect_Main_Menu_Open_Option_Focus_DrawStyle, _Zui_Effect_Main_Menu_Open_Option_Disabled_DrawStyle     },

    // 28 = HWND_EFFECT_MAIN_MENU_CLOSE
    { NULL, NULL, NULL     },

    // 29 = HWND_EFFECT_MAIN_MENU_CLOSE_BG
    { NULL, _Zui_Effect_Main_Menu_Close_Bg_Focus_DrawStyle, NULL     },

    // 30 = HWND_EFFECT_MAIN_MENU_CLOSE_TEXT
    { _Zui_Effect_Main_Menu_Close_Text_Normal_DrawStyle, _Zui_Effect_Main_Menu_Close_Text_Focus_DrawStyle, _Zui_Effect_Main_Menu_Close_Text_Disabled_DrawStyle     },

    // 31 = HWND_EFFECT_MAIN_MENU_CLOSE_OPTION
    { _Zui_Effect_Main_Menu_Close_Option_Normal_DrawStyle, _Zui_Effect_Main_Menu_Close_Option_Focus_DrawStyle, NULL     },

    // 32 = HWND_EFFECT_MAIN_MENU_ITEM
    { NULL, NULL, NULL     },

    // 33 = HWND_EFFECT_MAIN_MENU_ITEM_BG
    { NULL, _Zui_Effect_Main_Menu_Item_Bg_Focus_DrawStyle, NULL     },

    // 34 = HWND_EFFECT_MAIN_MENU_ITEM_TEXT
    { _Zui_Effect_Main_Menu_Item_Text_Normal_DrawStyle, _Zui_Effect_Main_Menu_Item_Text_Focus_DrawStyle, NULL     },

    // 35 = HWND_EFFECT_MAIN_MENU_ITEM_OPTION
    { _Zui_Effect_Main_Menu_Item_Option_Normal_DrawStyle, _Zui_Effect_Main_Menu_Item_Option_Focus_DrawStyle, NULL     },

    // 36 = HWND_EFFECT_POPUP_DIALOG
    { NULL, NULL, NULL     },

    // 37 = HWND_EFFECT_POPUP_DIALOG_BG
    { NULL, _Zui_Effect_Popup_Dialog_Bg_Focus_DrawStyle, NULL     },

    // 38 = HWND_EFFECT_POPUP_DIALOG_TEXT
    { _Zui_Effect_Popup_Dialog_Text_Normal_DrawStyle, _Zui_Effect_Popup_Dialog_Text_Focus_DrawStyle, NULL     },

    // 39 = HWND_EFFECT_POPUP_DIALOG_OPTION
    { _Zui_Effect_Popup_Dialog_Option_Normal_DrawStyle, _Zui_Effect_Popup_Dialog_Option_Focus_DrawStyle, NULL     },

    // 40 = HWND_EFFECT_INPUT_SOURCE
    { NULL, NULL, NULL     },

    // 41 = HWND_EFFECT_INPUT_SOURCE_BG
    { NULL, _Zui_Effect_Input_Source_Bg_Focus_DrawStyle, NULL     },

    // 42 = HWND_EFFECT_INPUT_SOURCE_TXT
    { _Zui_Effect_Input_Source_Txt_Normal_DrawStyle, _Zui_Effect_Input_Source_Txt_Focus_DrawStyle, NULL     },

    // 43 = HWND_EFFECT_INPUT_SOURCE_OPTION
    { _Zui_Effect_Input_Source_Option_Normal_DrawStyle, _Zui_Effect_Input_Source_Option_Focus_DrawStyle, NULL     },

};
