////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// AUDLANG_BG_PANE styles..


/////////////////////////////////////////////////////
// AUDLANG_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_87 },
    { CP_NOON, 0 },
};
#define _Zui_Audlang_Bg_C_Focus_DrawStyle _Zui_Audlang_Bg_C_Normal_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_86 },
    { CP_NOON, 0 },
};
#define _Zui_Audlang_Bg_L_Focus_DrawStyle _Zui_Audlang_Bg_L_Normal_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_88 },
    { CP_NOON, 0 },
};
#define _Zui_Audlang_Bg_R_Focus_DrawStyle _Zui_Audlang_Bg_R_Normal_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_BG_TITLE_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Bg_Title_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_924 },
    { CP_NOON, 0 },
};
#define _Zui_Audlang_Bg_Title_Text_Focus_DrawStyle _Zui_Audlang_Bg_Title_Text_Normal_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_BG_OK_BTN styles..


/////////////////////////////////////////////////////
// AUDLANG_LIST_PANE styles..


/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM0 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM0_FOCUS_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_124 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_ITEM0_ARROW_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_125 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_ITEM0_LANG_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_82 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_925 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_ITEM0_AUDIO_TYPE_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_186 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_187 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_ITEM0_AUDIO_TYPE2_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_188 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_189 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_ITEM0_L_SOUND_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_190 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_191 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_ITEM0_R_SOUND_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_192 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_193 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM1 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM1_FOCUS_BG styles..

#define _Zui_Audlang_Item1_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM1_ARROW_ICON styles..

#define _Zui_Audlang_Item1_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM1_LANG_TEXT styles..

#define _Zui_Audlang_Item1_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item1_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM1_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item1_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item1_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM1_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item1_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item1_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM1_L_SOUND_ICON styles..

#define _Zui_Audlang_Item1_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item1_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM1_R_SOUND_ICON styles..

#define _Zui_Audlang_Item1_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item1_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM2 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM2_FOCUS_BG styles..

#define _Zui_Audlang_Item2_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM2_ARROW_ICON styles..

#define _Zui_Audlang_Item2_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM2_LANG_TEXT styles..

#define _Zui_Audlang_Item2_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item2_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM2_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item2_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item2_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM2_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item2_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item2_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM2_L_SOUND_ICON styles..

#define _Zui_Audlang_Item2_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item2_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM2_R_SOUND_ICON styles..

#define _Zui_Audlang_Item2_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item2_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM3 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM3_FOCUS_BG styles..

#define _Zui_Audlang_Item3_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM3_ARROW_ICON styles..

#define _Zui_Audlang_Item3_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM3_LANG_TEXT styles..

#define _Zui_Audlang_Item3_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item3_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM3_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item3_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item3_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM3_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item3_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item3_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM3_L_SOUND_ICON styles..

#define _Zui_Audlang_Item3_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item3_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM3_R_SOUND_ICON styles..

#define _Zui_Audlang_Item3_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item3_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM4 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM4_FOCUS_BG styles..

#define _Zui_Audlang_Item4_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM4_ARROW_ICON styles..

#define _Zui_Audlang_Item4_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM4_LANG_TEXT styles..

#define _Zui_Audlang_Item4_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item4_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM4_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item4_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item4_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM4_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item4_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item4_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM4_L_SOUND_ICON styles..

#define _Zui_Audlang_Item4_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item4_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM4_R_SOUND_ICON styles..

#define _Zui_Audlang_Item4_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item4_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM5 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM5_FOCUS_BG styles..

#define _Zui_Audlang_Item5_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM5_ARROW_ICON styles..

#define _Zui_Audlang_Item5_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM5_LANG_TEXT styles..

#define _Zui_Audlang_Item5_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item5_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM5_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item5_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item5_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM5_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item5_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item5_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM5_L_SOUND_ICON styles..

#define _Zui_Audlang_Item5_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item5_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM5_R_SOUND_ICON styles..

#define _Zui_Audlang_Item5_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item5_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM6 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM6_FOCUS_BG styles..

#define _Zui_Audlang_Item6_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM6_ARROW_ICON styles..

#define _Zui_Audlang_Item6_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM6_LANG_TEXT styles..

#define _Zui_Audlang_Item6_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item6_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM6_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item6_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item6_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM6_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item6_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item6_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM6_L_SOUND_ICON styles..

#define _Zui_Audlang_Item6_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item6_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM6_R_SOUND_ICON styles..

#define _Zui_Audlang_Item6_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item6_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM7 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM7_FOCUS_BG styles..

#define _Zui_Audlang_Item7_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM7_ARROW_ICON styles..

#define _Zui_Audlang_Item7_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM7_LANG_TEXT styles..

#define _Zui_Audlang_Item7_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item7_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM7_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item7_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item7_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM7_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item7_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item7_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM7_L_SOUND_ICON styles..

#define _Zui_Audlang_Item7_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item7_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM7_R_SOUND_ICON styles..

#define _Zui_Audlang_Item7_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item7_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM8 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM8_FOCUS_BG styles..

#define _Zui_Audlang_Item8_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM8_ARROW_ICON styles..

#define _Zui_Audlang_Item8_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM8_LANG_TEXT styles..

#define _Zui_Audlang_Item8_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item8_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM8_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item8_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item8_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM8_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item8_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item8_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM8_L_SOUND_ICON styles..

#define _Zui_Audlang_Item8_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item8_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM8_R_SOUND_ICON styles..

#define _Zui_Audlang_Item8_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item8_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_LIST_ITEM9 styles..


/////////////////////////////////////////////////////
// AUDLANG_ITEM9_FOCUS_BG styles..

#define _Zui_Audlang_Item9_Focus_Bg_Focus_DrawStyle _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM9_ARROW_ICON styles..

#define _Zui_Audlang_Item9_Arrow_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM9_LANG_TEXT styles..

#define _Zui_Audlang_Item9_Lang_Text_Normal_DrawStyle _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle
#define _Zui_Audlang_Item9_Lang_Text_Focus_DrawStyle _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM9_AUDIO_TYPE_ICON styles..

#define _Zui_Audlang_Item9_Audio_Type_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item9_Audio_Type_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM9_AUDIO_TYPE2_ICON styles..

#define _Zui_Audlang_Item9_Audio_Type2_Icon_Normal_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item9_Audio_Type2_Icon_Focus_DrawStyle _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM9_L_SOUND_ICON styles..

#define _Zui_Audlang_Item9_L_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item9_L_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle

/////////////////////////////////////////////////////
// AUDLANG_ITEM9_R_SOUND_ICON styles..

#define _Zui_Audlang_Item9_R_Sound_Icon_Normal_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle
#define _Zui_Audlang_Item9_R_Sound_Icon_Focus_DrawStyle _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Audio_Language[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_AUDLANG_BG_PANE
    { NULL, NULL, NULL     },

    // 2 = HWND_AUDLANG_BG_C
    { _Zui_Audlang_Bg_C_Normal_DrawStyle, _Zui_Audlang_Bg_C_Focus_DrawStyle, NULL     },

    // 3 = HWND_AUDLANG_BG_L
    { _Zui_Audlang_Bg_L_Normal_DrawStyle, _Zui_Audlang_Bg_L_Focus_DrawStyle, NULL     },

    // 4 = HWND_AUDLANG_BG_R
    { _Zui_Audlang_Bg_R_Normal_DrawStyle, _Zui_Audlang_Bg_R_Focus_DrawStyle, NULL     },

    // 5 = HWND_AUDLANG_BG_TITLE_TEXT
    { _Zui_Audlang_Bg_Title_Text_Normal_DrawStyle, _Zui_Audlang_Bg_Title_Text_Focus_DrawStyle, NULL     },

    // 6 = HWND_AUDLANG_BG_OK_BTN
    { NULL, NULL, NULL     },

    // 7 = HWND_AUDLANG_LIST_PANE
    { NULL, NULL, NULL     },

    // 8 = HWND_AUDLANG_LIST_ITEM0
    { NULL, NULL, NULL     },

    // 9 = HWND_AUDLANG_ITEM0_FOCUS_BG
    { NULL, _Zui_Audlang_Item0_Focus_Bg_Focus_DrawStyle, NULL     },

    // 10 = HWND_AUDLANG_ITEM0_ARROW_ICON
    { NULL, _Zui_Audlang_Item0_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 11 = HWND_AUDLANG_ITEM0_LANG_TEXT
    { _Zui_Audlang_Item0_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item0_Lang_Text_Focus_DrawStyle, NULL     },

    // 12 = HWND_AUDLANG_ITEM0_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item0_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item0_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 13 = HWND_AUDLANG_ITEM0_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item0_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item0_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 14 = HWND_AUDLANG_ITEM0_L_SOUND_ICON
    { _Zui_Audlang_Item0_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item0_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 15 = HWND_AUDLANG_ITEM0_R_SOUND_ICON
    { _Zui_Audlang_Item0_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item0_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 16 = HWND_AUDLANG_LIST_ITEM1
    { NULL, NULL, NULL     },

    // 17 = HWND_AUDLANG_ITEM1_FOCUS_BG
    { NULL, _Zui_Audlang_Item1_Focus_Bg_Focus_DrawStyle, NULL     },

    // 18 = HWND_AUDLANG_ITEM1_ARROW_ICON
    { NULL, _Zui_Audlang_Item1_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 19 = HWND_AUDLANG_ITEM1_LANG_TEXT
    { _Zui_Audlang_Item1_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item1_Lang_Text_Focus_DrawStyle, NULL     },

    // 20 = HWND_AUDLANG_ITEM1_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item1_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item1_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 21 = HWND_AUDLANG_ITEM1_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item1_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item1_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 22 = HWND_AUDLANG_ITEM1_L_SOUND_ICON
    { _Zui_Audlang_Item1_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item1_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 23 = HWND_AUDLANG_ITEM1_R_SOUND_ICON
    { _Zui_Audlang_Item1_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item1_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 24 = HWND_AUDLANG_LIST_ITEM2
    { NULL, NULL, NULL     },

    // 25 = HWND_AUDLANG_ITEM2_FOCUS_BG
    { NULL, _Zui_Audlang_Item2_Focus_Bg_Focus_DrawStyle, NULL     },

    // 26 = HWND_AUDLANG_ITEM2_ARROW_ICON
    { NULL, _Zui_Audlang_Item2_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 27 = HWND_AUDLANG_ITEM2_LANG_TEXT
    { _Zui_Audlang_Item2_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item2_Lang_Text_Focus_DrawStyle, NULL     },

    // 28 = HWND_AUDLANG_ITEM2_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item2_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item2_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 29 = HWND_AUDLANG_ITEM2_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item2_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item2_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 30 = HWND_AUDLANG_ITEM2_L_SOUND_ICON
    { _Zui_Audlang_Item2_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item2_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 31 = HWND_AUDLANG_ITEM2_R_SOUND_ICON
    { _Zui_Audlang_Item2_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item2_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 32 = HWND_AUDLANG_LIST_ITEM3
    { NULL, NULL, NULL     },

    // 33 = HWND_AUDLANG_ITEM3_FOCUS_BG
    { NULL, _Zui_Audlang_Item3_Focus_Bg_Focus_DrawStyle, NULL     },

    // 34 = HWND_AUDLANG_ITEM3_ARROW_ICON
    { NULL, _Zui_Audlang_Item3_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 35 = HWND_AUDLANG_ITEM3_LANG_TEXT
    { _Zui_Audlang_Item3_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item3_Lang_Text_Focus_DrawStyle, NULL     },

    // 36 = HWND_AUDLANG_ITEM3_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item3_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item3_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 37 = HWND_AUDLANG_ITEM3_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item3_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item3_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 38 = HWND_AUDLANG_ITEM3_L_SOUND_ICON
    { _Zui_Audlang_Item3_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item3_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 39 = HWND_AUDLANG_ITEM3_R_SOUND_ICON
    { _Zui_Audlang_Item3_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item3_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 40 = HWND_AUDLANG_LIST_ITEM4
    { NULL, NULL, NULL     },

    // 41 = HWND_AUDLANG_ITEM4_FOCUS_BG
    { NULL, _Zui_Audlang_Item4_Focus_Bg_Focus_DrawStyle, NULL     },

    // 42 = HWND_AUDLANG_ITEM4_ARROW_ICON
    { NULL, _Zui_Audlang_Item4_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 43 = HWND_AUDLANG_ITEM4_LANG_TEXT
    { _Zui_Audlang_Item4_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item4_Lang_Text_Focus_DrawStyle, NULL     },

    // 44 = HWND_AUDLANG_ITEM4_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item4_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item4_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 45 = HWND_AUDLANG_ITEM4_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item4_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item4_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 46 = HWND_AUDLANG_ITEM4_L_SOUND_ICON
    { _Zui_Audlang_Item4_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item4_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 47 = HWND_AUDLANG_ITEM4_R_SOUND_ICON
    { _Zui_Audlang_Item4_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item4_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 48 = HWND_AUDLANG_LIST_ITEM5
    { NULL, NULL, NULL     },

    // 49 = HWND_AUDLANG_ITEM5_FOCUS_BG
    { NULL, _Zui_Audlang_Item5_Focus_Bg_Focus_DrawStyle, NULL     },

    // 50 = HWND_AUDLANG_ITEM5_ARROW_ICON
    { NULL, _Zui_Audlang_Item5_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 51 = HWND_AUDLANG_ITEM5_LANG_TEXT
    { _Zui_Audlang_Item5_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item5_Lang_Text_Focus_DrawStyle, NULL     },

    // 52 = HWND_AUDLANG_ITEM5_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item5_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item5_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 53 = HWND_AUDLANG_ITEM5_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item5_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item5_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 54 = HWND_AUDLANG_ITEM5_L_SOUND_ICON
    { _Zui_Audlang_Item5_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item5_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 55 = HWND_AUDLANG_ITEM5_R_SOUND_ICON
    { _Zui_Audlang_Item5_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item5_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 56 = HWND_AUDLANG_LIST_ITEM6
    { NULL, NULL, NULL     },

    // 57 = HWND_AUDLANG_ITEM6_FOCUS_BG
    { NULL, _Zui_Audlang_Item6_Focus_Bg_Focus_DrawStyle, NULL     },

    // 58 = HWND_AUDLANG_ITEM6_ARROW_ICON
    { NULL, _Zui_Audlang_Item6_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 59 = HWND_AUDLANG_ITEM6_LANG_TEXT
    { _Zui_Audlang_Item6_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item6_Lang_Text_Focus_DrawStyle, NULL     },

    // 60 = HWND_AUDLANG_ITEM6_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item6_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item6_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 61 = HWND_AUDLANG_ITEM6_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item6_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item6_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 62 = HWND_AUDLANG_ITEM6_L_SOUND_ICON
    { _Zui_Audlang_Item6_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item6_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 63 = HWND_AUDLANG_ITEM6_R_SOUND_ICON
    { _Zui_Audlang_Item6_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item6_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 64 = HWND_AUDLANG_LIST_ITEM7
    { NULL, NULL, NULL     },

    // 65 = HWND_AUDLANG_ITEM7_FOCUS_BG
    { NULL, _Zui_Audlang_Item7_Focus_Bg_Focus_DrawStyle, NULL     },

    // 66 = HWND_AUDLANG_ITEM7_ARROW_ICON
    { NULL, _Zui_Audlang_Item7_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 67 = HWND_AUDLANG_ITEM7_LANG_TEXT
    { _Zui_Audlang_Item7_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item7_Lang_Text_Focus_DrawStyle, NULL     },

    // 68 = HWND_AUDLANG_ITEM7_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item7_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item7_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 69 = HWND_AUDLANG_ITEM7_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item7_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item7_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 70 = HWND_AUDLANG_ITEM7_L_SOUND_ICON
    { _Zui_Audlang_Item7_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item7_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 71 = HWND_AUDLANG_ITEM7_R_SOUND_ICON
    { _Zui_Audlang_Item7_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item7_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 72 = HWND_AUDLANG_LIST_ITEM8
    { NULL, NULL, NULL     },

    // 73 = HWND_AUDLANG_ITEM8_FOCUS_BG
    { NULL, _Zui_Audlang_Item8_Focus_Bg_Focus_DrawStyle, NULL     },

    // 74 = HWND_AUDLANG_ITEM8_ARROW_ICON
    { NULL, _Zui_Audlang_Item8_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 75 = HWND_AUDLANG_ITEM8_LANG_TEXT
    { _Zui_Audlang_Item8_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item8_Lang_Text_Focus_DrawStyle, NULL     },

    // 76 = HWND_AUDLANG_ITEM8_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item8_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item8_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 77 = HWND_AUDLANG_ITEM8_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item8_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item8_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 78 = HWND_AUDLANG_ITEM8_L_SOUND_ICON
    { _Zui_Audlang_Item8_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item8_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 79 = HWND_AUDLANG_ITEM8_R_SOUND_ICON
    { _Zui_Audlang_Item8_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item8_R_Sound_Icon_Focus_DrawStyle, NULL     },

    // 80 = HWND_AUDLANG_LIST_ITEM9
    { NULL, NULL, NULL     },

    // 81 = HWND_AUDLANG_ITEM9_FOCUS_BG
    { NULL, _Zui_Audlang_Item9_Focus_Bg_Focus_DrawStyle, NULL     },

    // 82 = HWND_AUDLANG_ITEM9_ARROW_ICON
    { NULL, _Zui_Audlang_Item9_Arrow_Icon_Focus_DrawStyle, NULL     },

    // 83 = HWND_AUDLANG_ITEM9_LANG_TEXT
    { _Zui_Audlang_Item9_Lang_Text_Normal_DrawStyle, _Zui_Audlang_Item9_Lang_Text_Focus_DrawStyle, NULL     },

    // 84 = HWND_AUDLANG_ITEM9_AUDIO_TYPE_ICON
    { _Zui_Audlang_Item9_Audio_Type_Icon_Normal_DrawStyle, _Zui_Audlang_Item9_Audio_Type_Icon_Focus_DrawStyle, NULL     },

    // 85 = HWND_AUDLANG_ITEM9_AUDIO_TYPE2_ICON
    { _Zui_Audlang_Item9_Audio_Type2_Icon_Normal_DrawStyle, _Zui_Audlang_Item9_Audio_Type2_Icon_Focus_DrawStyle, NULL     },

    // 86 = HWND_AUDLANG_ITEM9_L_SOUND_ICON
    { _Zui_Audlang_Item9_L_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item9_L_Sound_Icon_Focus_DrawStyle, NULL     },

    // 87 = HWND_AUDLANG_ITEM9_R_SOUND_ICON
    { _Zui_Audlang_Item9_R_Sound_Icon_Normal_DrawStyle, _Zui_Audlang_Item9_R_Sound_Icon_Focus_DrawStyle, NULL     },

};
