////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON_BG styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON_BG_TOP styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Bg_Top_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_40 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_NEW_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_New_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_41 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_NEW_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_New_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_42 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_NEW_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_New_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_43 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_45 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_46 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_47 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_436 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_TEXT_PANE styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON_TEXT1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Text1_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_437 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_TEXT2 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Text2_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_435 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_PANE styles..


/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_INPUT_1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Password_Input_1_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_48 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Password_Input_1_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_49 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Password_Input_1_Disabled_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_50 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_INPUT_2 styles..

#define _Zui_Msgbox_Password_Input_2_Normal_DrawStyle _Zui_Msgbox_Password_Input_1_Normal_DrawStyle
#define _Zui_Msgbox_Password_Input_2_Focus_DrawStyle _Zui_Msgbox_Password_Input_1_Focus_DrawStyle
#define _Zui_Msgbox_Password_Input_2_Disabled_DrawStyle _Zui_Msgbox_Password_Input_1_Disabled_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_INPUT_3 styles..

#define _Zui_Msgbox_Password_Input_3_Normal_DrawStyle _Zui_Msgbox_Password_Input_1_Normal_DrawStyle
#define _Zui_Msgbox_Password_Input_3_Focus_DrawStyle _Zui_Msgbox_Password_Input_1_Focus_DrawStyle
#define _Zui_Msgbox_Password_Input_3_Disabled_DrawStyle _Zui_Msgbox_Password_Input_1_Disabled_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_INPUT_4 styles..

#define _Zui_Msgbox_Password_Input_4_Normal_DrawStyle _Zui_Msgbox_Password_Input_1_Normal_DrawStyle
#define _Zui_Msgbox_Password_Input_4_Focus_DrawStyle _Zui_Msgbox_Password_Input_1_Focus_DrawStyle
#define _Zui_Msgbox_Password_Input_4_Disabled_DrawStyle _Zui_Msgbox_Password_Input_1_Disabled_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_PRESSED_PANE styles..


/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_PRESSED_1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Password_Pressed_1_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_51 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_PRESSED_2 styles..

#define _Zui_Msgbox_Password_Pressed_2_Normal_DrawStyle _Zui_Msgbox_Password_Pressed_1_Normal_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_PRESSED_3 styles..

#define _Zui_Msgbox_Password_Pressed_3_Normal_DrawStyle _Zui_Msgbox_Password_Pressed_1_Normal_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_PASSWORD_PRESSED_4 styles..

#define _Zui_Msgbox_Password_Pressed_4_Normal_DrawStyle _Zui_Msgbox_Password_Pressed_1_Normal_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_PANE styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_CLEAR styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_CLEAR_LEFT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Clear_Left_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_53 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Clear_Left_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_54 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_CLEAR_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Clear_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_451 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Clear_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_452 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_OK styles..


/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_CANCEL_RIGHT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Cancel_Right_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_55 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Cancel_Right_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_56 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_BTN_CANCEL_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Cancel_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_453 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Btn_Cancel_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_454 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_COMMON_MSG_OK styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Msg_Ok_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_898 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Common_Msg_Ok_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_899 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_PANE styles..


/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM0 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Usb_List_Item0_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_124 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM0_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Usb_List_Item0_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_82 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Msgbox_Usb_List_Item0_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_714 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM1 styles..

#define _Zui_Msgbox_Usb_List_Item1_Focus_DrawStyle _Zui_Msgbox_Usb_List_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM1_TEXT styles..

#define _Zui_Msgbox_Usb_List_Item1_Text_Normal_DrawStyle _Zui_Msgbox_Usb_List_Item0_Text_Normal_DrawStyle
#define _Zui_Msgbox_Usb_List_Item1_Text_Focus_DrawStyle _Zui_Msgbox_Usb_List_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM2 styles..

#define _Zui_Msgbox_Usb_List_Item2_Focus_DrawStyle _Zui_Msgbox_Usb_List_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM2_TEXT styles..

#define _Zui_Msgbox_Usb_List_Item2_Text_Normal_DrawStyle _Zui_Msgbox_Usb_List_Item0_Text_Normal_DrawStyle
#define _Zui_Msgbox_Usb_List_Item2_Text_Focus_DrawStyle _Zui_Msgbox_Usb_List_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM3 styles..

#define _Zui_Msgbox_Usb_List_Item3_Focus_DrawStyle _Zui_Msgbox_Usb_List_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// MSGBOX_USB_LIST_ITEM3_TEXT styles..

#define _Zui_Msgbox_Usb_List_Item3_Text_Normal_DrawStyle _Zui_Msgbox_Usb_List_Item0_Text_Normal_DrawStyle
#define _Zui_Msgbox_Usb_List_Item3_Text_Focus_DrawStyle _Zui_Msgbox_Usb_List_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// EWS_FRAME styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ews_Frame_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_19 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DISASTER_SYMBOL styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Disaster_Symbol_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_208 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// AUTHOR_SYMBOL styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Author_Symbol_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_209 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DISASTER_LOCATION_STATUS_TXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Disaster_Location_Status_Txt_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_968 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// LOCATION_OF_DISASTER styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Location_Of_Disaster_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_969 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DISASTER_TYPE styles..


/////////////////////////////////////////////////////
// TYPE_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Type_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_970 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// TYPE_CONTENT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Type_Content_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_971 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DISASTER_DATE_AND_TIME styles..


/////////////////////////////////////////////////////
// DATE_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Date_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_972 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DATE_CONTENT styles..

#define _Zui_Date_Content_Normal_DrawStyle _Zui_Type_Content_Normal_DrawStyle

/////////////////////////////////////////////////////
// DISASTER_LONGITUDE styles..


/////////////////////////////////////////////////////
// LONGITUDE_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Longitude_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_973 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// LONGITUDE_CONTENT styles..

#define _Zui_Longitude_Content_Normal_DrawStyle _Zui_Type_Content_Normal_DrawStyle

/////////////////////////////////////////////////////
// DISASTER_CHARACTER styles..


/////////////////////////////////////////////////////
// CHARACTER_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Character_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_974 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// CHARACTER_CONTENT styles..

#define _Zui_Character_Content_Normal_DrawStyle _Zui_Type_Content_Normal_DrawStyle

/////////////////////////////////////////////////////
// REMARK styles..


/////////////////////////////////////////////////////
// REMARK_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Remark_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_975 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// REMARK_CONTENT styles..

#define _Zui_Remark_Content_Normal_DrawStyle _Zui_Type_Content_Normal_DrawStyle

/////////////////////////////////////////////////////
// REMARK_DESCRIPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Remark_Description_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_20 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_976 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EWS_FRAME_WASPADA styles..

#define _Zui_Ews_Frame_Waspada_Normal_DrawStyle _Zui_Ews_Frame_Normal_DrawStyle

/////////////////////////////////////////////////////
// DISASTER_SYMBOL2 styles..

#define _Zui_Disaster_Symbol2_Normal_DrawStyle _Zui_Disaster_Symbol_Normal_DrawStyle

/////////////////////////////////////////////////////
// AUTHOR_SYMBOL2 styles..

#define _Zui_Author_Symbol2_Normal_DrawStyle _Zui_Author_Symbol_Normal_DrawStyle

/////////////////////////////////////////////////////
// DISASTER_LOCATION_STATUS_TXT2 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Disaster_Location_Status_Txt2_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_977 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// LOCATION_OF_DISASTER2 styles..

#define _Zui_Location_Of_Disaster2_Normal_DrawStyle _Zui_Location_Of_Disaster_Normal_DrawStyle

/////////////////////////////////////////////////////
// REMARK_DESCRIPTION2 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Remark_Description2_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_20 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_978 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EWS_FRAME_WASPADA_SCROLL_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ews_Frame_Waspada_Scroll_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_21 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EWS_FRAME_WASPADA_SCROLL_BG_1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ews_Frame_Waspada_Scroll_Bg_1_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_22 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EWS_FRAME_WASPADA_SCROLL_BAR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ews_Frame_Waspada_Scroll_Bar_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_23 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};
#define _Zui_Ews_Frame_Waspada_Scroll_Bar_Focus_DrawStyle _Zui_Ews_Frame_Waspada_Scroll_Bar_Normal_DrawStyle

/////////////////////////////////////////////////////
// EWS_FRAME_WASPADA_SCROLL_BAR_1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ews_Frame_Waspada_Scroll_Bar_1_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_2 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Ews_Frame_Waspada_Scroll_Bar_1_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Message_Box[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_MSGBOX_COMMON
    { NULL, NULL, NULL     },

    // 2 = HWND_MSGBOX_COMMON_BG
    { NULL, NULL, NULL     },

    // 3 = HWND_MSGBOX_COMMON_BG_TOP
    { _Zui_Msgbox_Common_Bg_Top_Normal_DrawStyle, NULL, NULL     },

    // 4 = HWND_MSGBOX_COMMON_NEW_BG_L
    { _Zui_Msgbox_Common_New_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // 5 = HWND_MSGBOX_COMMON_NEW_BG_C
    { _Zui_Msgbox_Common_New_Bg_C_Normal_DrawStyle, NULL, NULL     },

    // 6 = HWND_MSGBOX_COMMON_NEW_BG_R
    { _Zui_Msgbox_Common_New_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // 7 = HWND_MSGBOX_COMMON_BG_L
    { _Zui_Msgbox_Common_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // 8 = HWND_MSGBOX_COMMON_BG_C
    { _Zui_Msgbox_Common_Bg_C_Normal_DrawStyle, NULL, NULL     },

    // 9 = HWND_MSGBOX_COMMON_BG_R
    { _Zui_Msgbox_Common_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // 10 = HWND_MSGBOX_COMMON_TITLE
    { _Zui_Msgbox_Common_Title_Normal_DrawStyle, NULL, NULL     },

    // 11 = HWND_MSGBOX_TEXT_PANE
    { NULL, NULL, NULL     },

    // 12 = HWND_MSGBOX_COMMON_TEXT1
    { _Zui_Msgbox_Common_Text1_Normal_DrawStyle, NULL, NULL     },

    // 13 = HWND_MSGBOX_COMMON_TEXT2
    { _Zui_Msgbox_Common_Text2_Normal_DrawStyle, NULL, NULL     },

    // 14 = HWND_MSGBOX_PASSWORD_PANE
    { NULL, NULL, NULL     },

    // 15 = HWND_MSGBOX_PASSWORD_INPUT_1
    { _Zui_Msgbox_Password_Input_1_Normal_DrawStyle, _Zui_Msgbox_Password_Input_1_Focus_DrawStyle, _Zui_Msgbox_Password_Input_1_Disabled_DrawStyle     },

    // 16 = HWND_MSGBOX_PASSWORD_INPUT_2
    { _Zui_Msgbox_Password_Input_2_Normal_DrawStyle, _Zui_Msgbox_Password_Input_2_Focus_DrawStyle, _Zui_Msgbox_Password_Input_2_Disabled_DrawStyle     },

    // 17 = HWND_MSGBOX_PASSWORD_INPUT_3
    { _Zui_Msgbox_Password_Input_3_Normal_DrawStyle, _Zui_Msgbox_Password_Input_3_Focus_DrawStyle, _Zui_Msgbox_Password_Input_3_Disabled_DrawStyle     },

    // 18 = HWND_MSGBOX_PASSWORD_INPUT_4
    { _Zui_Msgbox_Password_Input_4_Normal_DrawStyle, _Zui_Msgbox_Password_Input_4_Focus_DrawStyle, _Zui_Msgbox_Password_Input_4_Disabled_DrawStyle     },

    // 19 = HWND_MSGBOX_PASSWORD_PRESSED_PANE
    { NULL, NULL, NULL     },

    // 20 = HWND_MSGBOX_PASSWORD_PRESSED_1
    { _Zui_Msgbox_Password_Pressed_1_Normal_DrawStyle, NULL, NULL     },

    // 21 = HWND_MSGBOX_PASSWORD_PRESSED_2
    { _Zui_Msgbox_Password_Pressed_2_Normal_DrawStyle, NULL, NULL     },

    // 22 = HWND_MSGBOX_PASSWORD_PRESSED_3
    { _Zui_Msgbox_Password_Pressed_3_Normal_DrawStyle, NULL, NULL     },

    // 23 = HWND_MSGBOX_PASSWORD_PRESSED_4
    { _Zui_Msgbox_Password_Pressed_4_Normal_DrawStyle, NULL, NULL     },

    // 24 = HWND_MSGBOX_COMMON_BTN_PANE
    { NULL, NULL, NULL     },

    // 25 = HWND_MSGBOX_COMMON_BTN_CLEAR
    { NULL, NULL, NULL     },

    // 26 = HWND_MSGBOX_COMMON_BTN_CLEAR_LEFT_ARROW
    { _Zui_Msgbox_Common_Btn_Clear_Left_Arrow_Normal_DrawStyle, _Zui_Msgbox_Common_Btn_Clear_Left_Arrow_Focus_DrawStyle, NULL     },

    // 27 = HWND_MSGBOX_COMMON_BTN_CLEAR_TEXT
    { _Zui_Msgbox_Common_Btn_Clear_Text_Normal_DrawStyle, _Zui_Msgbox_Common_Btn_Clear_Text_Focus_DrawStyle, NULL     },

    // 28 = HWND_MSGBOX_COMMON_BTN_OK
    { NULL, NULL, NULL     },

    // 29 = HWND_MSGBOX_COMMON_BTN_CANCEL_RIGHT_ARROW
    { _Zui_Msgbox_Common_Btn_Cancel_Right_Arrow_Normal_DrawStyle, _Zui_Msgbox_Common_Btn_Cancel_Right_Arrow_Focus_DrawStyle, NULL     },

    // 30 = HWND_MSGBOX_COMMON_BTN_CANCEL_TEXT
    { _Zui_Msgbox_Common_Btn_Cancel_Text_Normal_DrawStyle, _Zui_Msgbox_Common_Btn_Cancel_Text_Focus_DrawStyle, NULL     },

    // 31 = HWND_MSGBOX_COMMON_MSG_OK
    { _Zui_Msgbox_Common_Msg_Ok_Normal_DrawStyle, _Zui_Msgbox_Common_Msg_Ok_Focus_DrawStyle, NULL     },

    // 32 = HWND_MSGBOX_USB_LIST_PANE
    { NULL, NULL, NULL     },

    // 33 = HWND_MSGBOX_USB_LIST_ITEM0
    { NULL, _Zui_Msgbox_Usb_List_Item0_Focus_DrawStyle, NULL     },

    // 34 = HWND_MSGBOX_USB_LIST_ITEM0_TEXT
    { _Zui_Msgbox_Usb_List_Item0_Text_Normal_DrawStyle, _Zui_Msgbox_Usb_List_Item0_Text_Focus_DrawStyle, NULL     },

    // 35 = HWND_MSGBOX_USB_LIST_ITEM1
    { NULL, _Zui_Msgbox_Usb_List_Item1_Focus_DrawStyle, NULL     },

    // 36 = HWND_MSGBOX_USB_LIST_ITEM1_TEXT
    { _Zui_Msgbox_Usb_List_Item1_Text_Normal_DrawStyle, _Zui_Msgbox_Usb_List_Item1_Text_Focus_DrawStyle, NULL     },

    // 37 = HWND_MSGBOX_USB_LIST_ITEM2
    { NULL, _Zui_Msgbox_Usb_List_Item2_Focus_DrawStyle, NULL     },

    // 38 = HWND_MSGBOX_USB_LIST_ITEM2_TEXT
    { _Zui_Msgbox_Usb_List_Item2_Text_Normal_DrawStyle, _Zui_Msgbox_Usb_List_Item2_Text_Focus_DrawStyle, NULL     },

    // 39 = HWND_MSGBOX_USB_LIST_ITEM3
    { NULL, _Zui_Msgbox_Usb_List_Item3_Focus_DrawStyle, NULL     },

    // 40 = HWND_MSGBOX_USB_LIST_ITEM3_TEXT
    { _Zui_Msgbox_Usb_List_Item3_Text_Normal_DrawStyle, _Zui_Msgbox_Usb_List_Item3_Text_Focus_DrawStyle, NULL     },

    // 41 = HWND_EWS_FRAME
    { _Zui_Ews_Frame_Normal_DrawStyle, NULL, NULL     },

    // 42 = HWND_DISASTER_SYMBOL
    { _Zui_Disaster_Symbol_Normal_DrawStyle, NULL, NULL     },

    // 43 = HWND_AUTHOR_SYMBOL
    { _Zui_Author_Symbol_Normal_DrawStyle, NULL, NULL     },

    // 44 = HWND_DISASTER_LOCATION_STATUS_TXT
    { _Zui_Disaster_Location_Status_Txt_Normal_DrawStyle, NULL, NULL     },

    // 45 = HWND_LOCATION_OF_DISASTER
    { _Zui_Location_Of_Disaster_Normal_DrawStyle, NULL, NULL     },

    // 46 = HWND_DISASTER_TYPE
    { NULL, NULL, NULL     },

    // 47 = HWND_TYPE_TITLE
    { _Zui_Type_Title_Normal_DrawStyle, NULL, NULL     },

    // 48 = HWND_TYPE_CONTENT
    { _Zui_Type_Content_Normal_DrawStyle, NULL, NULL     },

    // 49 = HWND_DISASTER_DATE_AND_TIME
    { NULL, NULL, NULL     },

    // 50 = HWND_DATE_TITLE
    { _Zui_Date_Title_Normal_DrawStyle, NULL, NULL     },

    // 51 = HWND_DATE_CONTENT
    { _Zui_Date_Content_Normal_DrawStyle, NULL, NULL     },

    // 52 = HWND_DISASTER_LONGITUDE
    { NULL, NULL, NULL     },

    // 53 = HWND_LONGITUDE_TITLE
    { _Zui_Longitude_Title_Normal_DrawStyle, NULL, NULL     },

    // 54 = HWND_LONGITUDE_CONTENT
    { _Zui_Longitude_Content_Normal_DrawStyle, NULL, NULL     },

    // 55 = HWND_DISASTER_CHARACTER
    { NULL, NULL, NULL     },

    // 56 = HWND_CHARACTER_TITLE
    { _Zui_Character_Title_Normal_DrawStyle, NULL, NULL     },

    // 57 = HWND_CHARACTER_CONTENT
    { _Zui_Character_Content_Normal_DrawStyle, NULL, NULL     },

    // 58 = HWND_REMARK
    { NULL, NULL, NULL     },

    // 59 = HWND_REMARK_TITLE
    { _Zui_Remark_Title_Normal_DrawStyle, NULL, NULL     },

    // 60 = HWND_REMARK_CONTENT
    { _Zui_Remark_Content_Normal_DrawStyle, NULL, NULL     },

    // 61 = HWND_REMARK_DESCRIPTION
    { _Zui_Remark_Description_Normal_DrawStyle, NULL, NULL     },

    // 62 = HWND_EWS_FRAME_WASPADA
    { _Zui_Ews_Frame_Waspada_Normal_DrawStyle, NULL, NULL     },

    // 63 = HWND_DISASTER_SYMBOL2
    { _Zui_Disaster_Symbol2_Normal_DrawStyle, NULL, NULL     },

    // 64 = HWND_AUTHOR_SYMBOL2
    { _Zui_Author_Symbol2_Normal_DrawStyle, NULL, NULL     },

    // 65 = HWND_DISASTER_LOCATION_STATUS_TXT2
    { _Zui_Disaster_Location_Status_Txt2_Normal_DrawStyle, NULL, NULL     },

    // 66 = HWND_LOCATION_OF_DISASTER2
    { _Zui_Location_Of_Disaster2_Normal_DrawStyle, NULL, NULL     },

    // 67 = HWND_REMARK_DESCRIPTION2
    { _Zui_Remark_Description2_Normal_DrawStyle, NULL, NULL     },

    // 68 = HWND_EWS_FRAME_WASPADA_SCROLL_BG
    { _Zui_Ews_Frame_Waspada_Scroll_Bg_Normal_DrawStyle, NULL, NULL     },

    // 69 = HWND_EWS_FRAME_WASPADA_SCROLL_BG_1
    { _Zui_Ews_Frame_Waspada_Scroll_Bg_1_Normal_DrawStyle, NULL, NULL     },

    // 70 = HWND_EWS_FRAME_WASPADA_SCROLL_BAR
    { _Zui_Ews_Frame_Waspada_Scroll_Bar_Normal_DrawStyle, _Zui_Ews_Frame_Waspada_Scroll_Bar_Focus_DrawStyle, NULL     },

    // 71 = HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1
    { _Zui_Ews_Frame_Waspada_Scroll_Bar_1_Normal_DrawStyle, _Zui_Ews_Frame_Waspada_Scroll_Bar_1_Focus_DrawStyle, NULL     },

};
