////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2013 10:00:02]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// EPOP_BG_PANE styles..


/////////////////////////////////////////////////////
// EPOP_FRAME styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Epop_Frame_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EPOP_IMG_DL styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Epop_Img_Dl_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_326 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EPOP_IMG_DR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Epop_Img_Dr_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_327 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// EPOP_IMG_U styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Epop_Img_U_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_328 },
    { CP_NOON, 0 },
};

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Epop[] =
{
    // 0 = HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // 1 = HWND_EPOP_BG_PANE
    { NULL, NULL, NULL     },

    // 2 = HWND_EPOP_FRAME
    { _Zui_Epop_Frame_Normal_DrawStyle, NULL, NULL     },

    // 3 = HWND_EPOP_IMG_DL
    { _Zui_Epop_Img_Dl_Normal_DrawStyle, NULL, NULL     },

    // 4 = HWND_EPOP_IMG_DR
    { _Zui_Epop_Img_Dr_Normal_DrawStyle, NULL, NULL     },

    // 5 = HWND_EPOP_IMG_U
    { _Zui_Epop_Img_U_Normal_DrawStyle, NULL, NULL     },

};
